// js/indicacionesDB.js

const indicacionesDB = [
    {
        id: 1,
        titulo: "ANTECEDENTES",
        tipo: "urgencia",
        contenido: `AM: NO | AL: NO | FCOS: NO| CX: NO| HOSP: NO | PNI AL DIA`
    },
    {
        id: 2,
        titulo: "EXAMEN FÍSICO NORMAL",
        tipo: "urgencia",
        contenido: `BUEN ESTADO GENERAL, LLENE CAPILAR NORMAL, MUCOSAS ROSADAS
FARINGE SIN ERITEMA, SIN PLACAS DE PUS.
OTOSCOPIA NORMAL, NO PALPO ADENOPATÍAS
SIN RETRACCIÓN DE PB, SIN SIGNOS DE DIFICULTAD RESPIRATORIA,
RR2T NO AUSCULTO SOPLOS, MP (+) SRA
ABDOMEN RHA (+) BLANDO DEPRESIBLE, SIN SIGNOS DE IRRITACION PERITONEAL BLUMBERG (-), SIN MASAS, SIN VISCEROMEGALIAS.
EEII SIN EDEMA, SIN LESIONES EN PIEL, PULSOS PRESENTES Y SIMETRICOS`
    },
    {
        id: 3,
        titulo: "EXAMEN NEUROLÓGICO NORMAL",
        tipo: "urgencia",
        contenido: `ABDOMEN RHA (+) BLANDO DEPRESIBLE, SIN SIGNOS DE IRRITACION PERITONEAL BLUMBERG (-), SIN MASAS, SIN VISCEROMEGALIAS.
EEII SIN EDEMA, SIN LESIONES EN PIEL, PULSOS PRESENTES Y SIMETRICOS`
    },
    
    {
        id: 4,
        titulo: "ABCDE DEL TRAUMA",
        tipo: "urgencia",
        contenido: `A: VIA AEREA PERMEABLE, SIN COLLAR CERVICAL
B: MURMULLO PULMONAR PRESENTES, SIN RUIDOS AGREGADOS, SATURANDO X% AMBIENTAL, SIN RETRACCIONES
C: PAM X, FC X, LLENE CAPILAR MENOR 2 SEGUNDOS, SIN LESIONES, FRACTURAS NI SANGRADO EVIDENTE
D: GLASGOW 15, PUPILAS ISOCORICAS  Y REACTIVAS, MOVILIZA 4 EXTREMIDADES, SIN FOCALIDAD NEUROLOGICA`
    },

    {
        id: 5,
        titulo: "PACIENTE CUADRO RESPIRATORIO",
        tipo: "urgencia",
        contenido: `ANAMNESIS RESFRÍO
AM: NIEGA
FÁRMACOS: NIEGA
ALERGIAS: NIEGA
QUIRÚRGICOS: NIEGA

HC: paciente con cuadro de X dias de evolucion caracterizado por coriza, tos, odinofagia, sin disnea, fiebre objetivada en 3X°C, asociado a náuseas, vómitos u otra sintomatología

Examen Físico:
BUEN aspecto general
Bien hidratado y perfundido
Faringe eritematosa, sin placas ni exudados, sin abombamientos ni desviaciones, no palpo adenopatias
Sin apremio respiratorio. RR2T, no ausculto soplos. MP (+) simétric, no ausculto rudios agregados

INDICACIONES:
- DICLOFENACO 75MG IM, BETAMETASONA 4MG IM
- RÉGIMEN HABITUAL, HIDRATACION ABUNDANTE
- USO DE MASCARILLA, LAVADO DE MANOS FRECUENTE
- PARACETAMOL 500 MG 2 COMP CADA 6HRS
- IBUPROFENO 1 COMP SOS EN CASO DE FIEBRE O DOLOR QUE NO CEDE (MAX CADA 8H POR 3 DIAS)
- CLORFENAMINA 4 MG 1 COMP CADA 8H POR 3 DÍAS.
- URGENCIAS EN CASO DE: DIFICULTAD RESPIRATORIA, FIEBRE QUE NO CEDE MAS DE 3 DÍAS, SINTOMAS DE ALARMA EXPLICADOS O CUALQUIER DETERIORO DEL ESTADO GENERAL

INYECTABLES:
- VIADIL 5MG/ML + METAMIZOL 1G/2ML IM
- DICLOFENACO 75MG/3ML IM + Betametasona 4mg im`
    },

    {
        id: 6,
        titulo: "RINOFARINGITIS AGUDA",
        tipo: "urgencia",
        contenido: `- REPOSO EN CASA
- RÉGIMEN HABITUAL
- PARACETAMOL 500 MG 2 COMP EN CASO DE FIEBRE O DOLOR (MAX CADA 6H)
- IBUPROFENO 1 COMP EN CASO DE FIEBRE O DOLOR QUE NO CEDE (MAX CADA 8H)
- CLORFENAMINA 4 MG 1 COMP CADA 8H POR 3 DIAS.
- URGENCIAS EN CASO DE: DIFICULTAD RESPIRATORIA, FIEBRE QUE NO CEDE MAS DE 3 DÍAS O SOS.`
    },


    {
        id: 7,
        titulo: "CÓLICO ABDOMINAL",
        tipo: "urgencia",
        contenido: `- REGIMEN LIVIANO, NO CONSUMIR IRRITANTES NI COMIDAS GRASAS.
- DOLOSPAM 1 COMP CADA 8H POR 3 DIAS.
- DOMPERIDONA 10MG 1 COMP CADA 8H POR 3 DIAS.
- OMEPRAZOL 20 MG 1 COMP CADA 12 H POR 5 DIAS.
- CONTROL EN SU CESFAM CON MEDICO EN CASO DE PERSISTENCIA DE SINTOMAS PARA ESTUDIO.
- ACUDIR A URGENCIAS EN CASO DE FIEBRE O DOLOR QUE EMPEORA, VOMITOS QUE NO CEDEN, COLORACION AMARILLA DE PIEL, O EN CASO NECESARIO.
`
    },
    
    {
        id: 8,
        titulo: "GASTROENTERITIS AGUDA",
        tipo: "urgencia",
        contenido: `- REPOSO EN CASA
- REGIMEN LIVIANO, ABUNDANTE LIQUIDO, TODO COCIDO
- DOLOSPAM 1 COMP CADA 8H POR 3 DIAS.
- DOMPERIDONA 10MG 1 COMP CADA 8H POR 3 DIAS.
- SALES REHIDRATANTES 200 CC DESPUES DE CADA VOMITO O DIARREA.
- URGENCIAS EN CASO DE FIEBRE QUE NO CEDE, VOMITOS INCONTROLABLES, DOLOR QUE EMPEORA O SOS.`
    },
    
    
    {
        id: 9,
        titulo: "GASTROENTERITIS AGUDA PARTICULAR",
        tipo: "urgencia",
        contenido: `- REPOSO EN CASA
- REGIMEN LIVIANO, ABUNDANTE LIQUIDO, TODO COCIDO
- DOLOSPAM 1 COMP CADA 8H POR 2 DIAS.
- ONDANSETRON 8MG VO CADA 8HRS X2 DIAS
- LOPERAMIDA 2MG VO CADA 6HRS X2DIAS
- BEBER SALES REHIDRATANTESDURANTE EL DIA, ADICIONALMENTE REPONER 200 CC DESPUES DE CADA VOMITO O DIARREA.
- URGENCIAS EN CASO DE FIEBRE QUE NO CEDE, VOMITOS INCONTROLABLES, DOLOR QUE EMPEORA O SOS.`
    },
    
    
    {
        id: 10,
        titulo: "GASTROENTERITIS AGUDA PEDIÁTRICA",
        tipo: "urgencia",
        contenido: `- REPOSO EN CASA 7 DIAS
- REGIMEN LIVIANO A TOLERANCIA, TODO COCIDO
- PARACETAMOL 100MG/ML GOTAS EN CASO DE FIEBRE O DOLOR (MAX CADA 6H)
- IBUPROFENO 200MG/5ML ML EN CASO DE FIEBRE O DOLOR QUE NO CEDE (MAX CADA 8H)
- SALES REHIDRATANTES 100 CC DESPUES DE CADA VOMITO O DIARREA.
- SE SUGIERE INICIO DE PERENTERYL O BIOFLORA 1 SOBRE CADA 12 H POR 5 DIAS.
- URGENCIAS EN CASO DE: NO ORINAR MAS DE 12 HRS, DOLOR ABDOMINAL QUE NO CEDE O EMPEORA, FIEBRE QUE NO CEDE EN MAS DE 3 DIAS, DESHIDRATACION, NO TOLERAR NADA VIA ORAL O SOS. 

INDICACIONES EN NEONATO
- LACTANCIA MATERNA EXCLUSIVA Y/O FÓRMULA LIBRE DEMANDA
- REPOSO EN DOMICILIO POR 7 DÍAS, EVITAR CONTACTOS RESPIRATORIOS, DORMIR SEGURO.
- MANTENER VIT ACD 400 UI CADA DIA VIA ORAL.
- ACUDIR A CLÍNICA DE LACTANCIA.
- BIOGAIA GOTAS. ADMINISTRAR 5 GOTAS VÍA ORAL CADA DÍA.
- ACUDIR AL SERVICIO DE URGENCIA ANTE SIGNOS DE ALARMA (FIEBRE, MAL ASPECTO GENERAL, DIFICULTAD RESPIRATORIA, RECHAZO ALIMENTARIO, COMPROMISO DE CONCIENCIA, ETC)`

    },
    
    {
        id: 11,
        titulo: "AMIGDALITIS AGUDA",
        tipo: "urgencia",
        contenido: `- REPOSO EN CASA
- PREFIRIR ALIMENTOS BLANDOS Y LIQUIDOS FRIOS
- PARACETAMOL 500 MG 2 COMP EN CASO DE FIEBRE O DOLOR (MAX CADA 6H)
- IBUPROFENO 1 COMP EN CASO DE FIEBRE O DOLOR QUE NO CEDE (MAX CADA 8H)
- AMOXICILINA 500 MG 1 COMP CADA 8 H POR 10 DIAS
- URGENCIAS EN CASO DE: DIFICULTAD RESPIRATORIA, FIEBRE QUE NO CEDE MAS DE 3 DIAS, DIFICULTAD A LA APERTURA BUCAL O DETERIORO CLINICO GENERAL`
    },

    {
        id: 12,
        titulo: "AMIGDALITIS AGUDA PEDIÁTRICA",
        tipo: "urgencia",
        contenido: `- REPOSO EN CASA
- PREFIRIR ALIMENTOS BLANDOS Y LIQUIDOS FRIOS
- PARACETAMOL 500 MG 1/2 COMP EN CASO DE FIEBRE O DOLOR (MÁX CADA 6H)
- IBUPROFENO 200/5ml 5ml en CASO DE FIEBRE O DOLOR QUE NO CEDE (MAX CADA 8H)
- AMOXICILINA 500/5ml 5ml cada 12hrs por 10 dias
- URGENCIAS EN CASO DE: DIFICULTAD RESPIRATORIA, FIEBRE QUE NO CEDE MAS DE 3 DIAS O EN CASO NECESARIO.`
    },
    
    {
        id: 13,
        titulo: "BRONQUITIS AGUDA",
        tipo: "urgencia",
        contenido: `- REPOSO EN CASA
- REGIMEN HABITUAL
- PARACETAMOL 500 MG 2 COMP EN CASO DE FIEBRE O DOLOR (MAX CADA 6H)
- IBUPROFENO 1 COMP EN CASO DE FIEBRE O DOLOR QUE NO CEDE (MAX CADA 8H)
- CLORFENAMINA 4 MG 1 COMP CADA 8H POR 3 DIAS.
- SALBUTAMOL 2 PUFF CADA 6H POR 7 DIAS CON AEROCAMARA
- PREDNISONA 20 MG 1 COMP CADA 12 H POR 3 DIAS
- URGENCIAS EN CASO DE: DIFICULTAD RESPIRATORIA, FIEBRE QUE NO CEDE MAS DE 3 DIAS O EN CASO NECESARIO.`
    },
    
    {
        id: 14,
        titulo: "BRONQUITIS AGUDA PEDIÁTRICA",
        tipo: "urgencia",
        contenido: `- REPOSO EN CASA POR 5 DIAS
- REGIMEN HABITUAL, ABUNDANTE LIQUIDO
- PARACETAMOL 100MG/ML 57 GOTAS EN CASO DE FIEBRE O DOLOR (MAX CADA 6H)
- IBUPROFENO 200MG/5ML 5 CC EN CASO DE FIEBRE O DOLOR QUE NO CEDE (MAX CADA 8H)
- SALBUTAMOL 2 PUFF CADA 6H POR 7 DIAS CON AEROCAMARA
- PREDNISONA 20MG/5ML 5 CC CADA 12 H POR 3 DIAS
- CONTROL EN SU SALA IRA PEDIR HORA EN SU CESFAM.
- URGENCIAS SOS: DIFICULTAD RESPIRATORIA, COLORACIÓN AZULADA DE LABIOS, DOLOR QUE EMPEORA, FIEBRE MAS DE 3 DÍAS O EN CASO NECESARIO.`
    },
    
    {
        id: 15,
        titulo: "RESFRÍO PEDIATRÍA",
        tipo: "urgencia",
        contenido: `- REPOSO EN CASA 5 DIAS
- REGIMEN HABITUAL, ABUNDANTE LIQUIDO
- PARACETAMOL 100MG/ML 57 GOTAS EN CASO DE FIEBRE O DOLOR (MAX CADA 6H)
- IBUPROFENO 200MG/5ML 5 CC EN CASO DE FIEBRE O DOLOR QUE NO CEDE (MAX CADA 8H)
- URGENCIAS SOS: DIFICULTAD RESPIRATORIA, COLORACIÓN AZULADA DE LABIOS, DOLOR QUE EMPEORA, FIEBRE MAS DE 3 DÍAS O EN CASO NECESARIO`
    },
    
    {
        id: 16,
        titulo: "OTITIS MEDIA AGUDA",
        tipo: "urgencia",
        contenido: `- REPOSO EN CASA
- REGIMEN HABITUAL
- NO MOJAR OIDO.
- PARACETAMOL 500 MG 2 COMP EN CASO DE FIEBRE O DOLOR (MAX CADA 6H)
- IBUPROFENO 1 COMP EN CASO DE FIEBRE O DOLOR QUE NO CEDE (MAX CADA 8H)
- CLORFENAMINA 4 MG 1 COMP CADA 8H POR 3 DIAS.
- AMOXICILINA 500 MG 1 COMP CADA 8H POR 7 DIAS
- URGENCIAS EN CASO DE: DIFICULTAD RESPIRATORIA, FIEBRE QUE NO CEDE MAS DE 3 DIAS O EN CASO NECESARIO.`
    },
    
    {
        id: 17,
        titulo: "OTITIS EXTERNA",
        tipo: "urgencia",
        contenido: `- NO EXPONER A AMBIENTES FRIOS. NO MOJAR OIDOS, USAR PROTECTOR OTICO AL VIENTE (GORRO, OREJERA)
- OTICUM GOTAS (POLIMIXINA B 1.000.000 U.I.; NEOMICINA 0.35 G; BETAMETASONA DISODIO FOSFATO 0.1 G; LIDOCAÍNA CLORHIDRATO 2 G.) APLICAR 4 GOTAS CADA 8HRS POR 7 DIAS EN EL CONDUCTO AUDITIVO MANTENER POSICION DE LADO POR 1 MINUTO LUEGO DE APLICAR LAS GOTAS
- PARACETAMOL 500MG 2 COMPRIMIDOS VO CADA 6HRS POR 5DIAS 
- IBUPROFENO 400MG 1 COMPRIMIDO VO CADA 8HRS POR 3DIAS 
- CONTROL SOS EN SU CESFAM
- URGENCIAS EN CASO DE: DIFICULTAD RESPIRATORIA, FIEBRE QUE NO CEDE MAS DE 3 DIAS O EN CASO NECESARIO.`
    },
    
    {
        id: 18,
        titulo: "NEUMONÍA",
        tipo: "urgencia",
        contenido: `- REPOSO EN CASA
- REGIMEN HABITUAL
- PARACETAMOL 500 MG 2 COMP EN CASO DE FIEBRE O DOLOR (MAX CADA 6H)
- IBUPROFENO 1 COMP EN CASO DE FIEBRE O DOLOR QUE NO CEDE (MAX CADA 8H)
- CLORFENAMINA 4 MG 1 COMP CADA 8H POR 3 DIAS.
- SALBUTAMOL 2 PUFF CADA 6H POR 7 DIAS CON AEROCAMARA
- PREDNISONA 20 MG 1 COMP CADA 12 H POR 3 DIAS
- AMOXICILINA 500 MG 1 COMP CADA 8H POR 7DIAS
- URGENCIAS EN CASO DE: DIFICULTAD RESPIRATORIA, FIEBRE QUE NO CEDE MAS DE 3 DIAS O EN CASO NECESARIO.`
    },
    
    {
        id: 19,
        titulo: "NEUMONÍA ATÍPICA",
        tipo: "urgencia",
        contenido: `- HIDRATACION ABUNDANTE
- PARACETAMOL 500MG 2 COMPRIMIDOS VO CADA 6HRS X5D
- IBUPROFENO 400MG 1 COMPRIMIDO VO CADA 8HRS X3D
- SALBUTAMOL 4PUFF CADA 4HRS
- CLARITROMICINA 500MG 1 COMPRIMIDO VO CADA 12HRS X7D
- PROBIOTICOS!!! (ATB PRODUCE DIARREA)
- URGENCIAS EN CASO DE: DIFICULTAD RESPIRATORIA, FIEBRE QUE NO CEDE MAS DE 3 DIAS O EN CASO NECESARIO.`
    },
    
    {
        id: 20,
        titulo: "CRISIS ASMÁTICA",
        tipo: "urgencia",
        contenido: `- REPOSO EN CASA
- REGIMEN HABITUAL
- SALBUTAMOL 2 PUFF CADA 4 H POR 7 DIAS CON AEROCAMARA
- PREDNISONA 20 MG 1 COMP CADA 12 H POR 5 DIAS.
- CONTROL EN SU SALA ERA EN SU CESFAM, PEDIR HORA.
- URGENCIAS EN CASO DE FIEBRE, DIFICULTAD RESPIRATORIA O SOS.`
    },
    
    {
        id: 21,
        titulo: "LUMBAGO MECÁNICO",
        tipo: "urgencia",
        contenido: `- REPOSO RELATIVO, EVITE EL REPOSO EN CAMA
- MANTENGA EL MAYOR GRADO DE ACTIVIDAD FÍSICA DIARIA POSIBLE QUE LE PERMITA SU DOLOR
- HAGA EJERCICIO DE MANERA REGULAR
- CALOR TIBIO LOCAL 20MIN 3 VECES AL DÍA
- PARACETAMOL 500 MG. 2 COMPRIMIDOS CADA 8 HORAS VÍA ORAL POR 5 DÍAS.
- CELECOXIB 200 MG. 1 COMPRIMIDO CADA 12 HORAS VÍA ORAL POR 3 DÍAS.
- CICLOBENZAPRINA 10 MG. 1 COMPRIMIDO POR NOCHE VIA ORAL POR 3 DIAS. (PRODUCE SOMNOLENCIA, NO USAR ESTE MEDICAMENTO SI MANEJA VEHICULOS O MAQUINARIA)
- CONTROL SOS EN CASO NECESARIO EN SU CESFAM`
    },

    {
        id: 22,
        titulo: "LARINGITIS",
        tipo: "urgencia",
        contenido: `- REPOSO EN DOMICILIO POR 3 DÍAS
- REGIMEN HABITUAL, FRACCIONADO, LIQUIDOS ABUNDANTES.
- ASEO NASAL FRECUENTE
- PARACETAMOL 100 MG/ML GOTAS,
- IBUPROFENO 200/5 CADA 8H POR 3 DÍAS
- PREDNISONA 20/5 CADA 12H POR 3 DÍAs
- CONTROL EN SU SALA IRA EN 48H PARA VIGILAR EVOLUCIÓN
- URGENCIAS EN CASO DE: DIFICULTAD RESPIRATORIA, FIEBRE QUE NO CEDE MAS DE 3 DIAS O EN CASO NECESARIO`
    },
    
    {
        id: 23,
        titulo: "LARINGITIS MODERADA/SEVERA",
        tipo: "urgencia",
        contenido: `- NBZ ADRENALINA CORRIENTE 4 ML (4 MG QUE SON 4 AMPOLLAS) EN MAYORES DE 4.5 KG DURANTE 10 - 15 MIN CON FLUJO DE 4-6 LT/MIN
- NBZ ADRENALINA RACÉMICA 0.05 ML/KG (MINIMO DE 0,5 QUE ES 1 AMP) (COMPLETAR 4 CC CON SUERO FISIOLÓGICO)
- NEBULIZAR CON O2 A 6 LTS EN LARINGITIS.`
    },
    
    {
        id: 24,
        titulo: "VARICELA",
        tipo: "urgencia",
        contenido: `- REPOSO EN CASA HASTA QUE TODAS LAS LESIONES SEAN COSTRA
- REGIMEN HABITUAL, ABUNDANTE LÍQUIDO
- (DEJA DE CONTAGIAR CUANDO TODAS LAS LESIONES SEAN COSTRA)
- EVITAR EXPOSICIÓN AL SOL
- PARACETAMOL
- IBUPROFENO
- UÑAS CORTAS, EVITAR GRATAJE.
- NO ESTAR EN CONTACTO CON EMBARAZADAS, LACTANTES MENORES DE 6MESES, INMUNODEPRIMIDOS, Y PERSONAS MAYORES DE 12 AÑOS QUE NO HAYAN TENIDO VARICELA.
- URGENCIAS EN CASO DE: DIFICULTAD RESPIRATORIA, FIEBRE QUE NO CEDE, DIFICULTAD PARA CAMINAR, INFECCION DE LAS LESIONES O EN CASO NECESARIO.`
    },
    
    {
        id: 25,
        titulo: "ESGUINCE",
        tipo: "urgencia",
        contenido: `OPCIÓN 1:
- REPOSO DEPORTIVO 10 DIAS
- REPOSO EN CASA POR 5 DIAS CON PIE EN ALTO
- COMPRESIÓN Y/O VENDAJE DE LA EXTREMIDAD
- HIELO LOCAL 30 MINUTOS 3 VECES POR DIA
- IBUPROFENO 400MG CADA 8H POR 3 DIAS
- PARACETAMOL 500 MG 2 COMP CADA 8H POR 3 DIAS.
- CONTROL SOS EN SU POLICLINICO EN CESFAM EN CASO DE PERSISTENCIA DEL DOLOR.

OPCIÓN 2:
- REPOSO EN CASA POR 3 DIAS
- REPOSO DEPORTIVO, USO DE TOBILLERA
- FRIO LOCAL, PIE EN ALTO
- DICLOFENACO 50 MG 1 COMP CADA 8H POR 3 DIAS
- PARACETAMOL 500 MG 2 COMP CADA 8H POR 3 DIAS
- URGENCIAS SOS.
- CONTROL EN SU CONSULTORIO EN CASO DE AUMENTO DE VOLUMEN MAYOR, DOLOR QUE NO CEDE O EMPEORA O EN CASO NECESARIO.`
    },

    {
        id: 26,
        titulo: "INFECCIÓN URINARIA",
        tipo: "urgencia",
        contenido: `- REPOSO RELATIVO
- ABUNDANTE LIQUIDO
- CIPROFLOXACINO/CEFADROXILO/NITROFURANTOINA
- DOLOSPAM 1 COMP CADA 8H POR 3 DIAS
- PARACETAMOL 500MG 2 COM CADA 8H POR 3 DIAS
- NO BEBER LIQUIDO QUE IRRITE LA VEJIGA: ALCOHOL, CAFE, TE.
- MEDIDAS DE HIGIENE (SE EDUCA.
- USO DE ROPA INTERIOR DE ALGODON, EVITAR LA HUMEDAD.
- CONTROL EN SU CESFAM CON RESULTADO DE UROCULTIVO EN 48H
- CONTROL EN URGENCIAS EN CASO DE: FIEBRE, DOLOR DE ESPALDA, VOMITOS O EN CASO NECESARIO`
    },

    {
        id: 27,
        titulo: "INFECCIÓN URINARIA PEDIÁTRICA",
        tipo: "urgencia",
        contenido: `- RÉGIMEN HABITUAL, PRIORIZAR INGESTA DE LÍQUIDOS.
- CEFADROXILO 250MG/5ML 50MG/KG O CEFPODOXIMO JBE 100 MG/5ML.
- ADMINISTRAR CC VIA ORAL CADA 12 HORAS (HASTA RESULTADOS DE UROCULTIVO)
- PARACETAMOL GOTAS. ADMINISTRAR GOTAS VO SOS A FIEBRE>38.5°C (MAX C/6 HORAS)
- IBUPROFENO JBE 200MG/5ML. ADMINISTRAR 5 CC VO SOS A FIEBRE > 38.5°C (MAX C/8 HORAS)
- CONTROL MEDICO EN SU CESFAM UNA VEZ TERMINADO EL TRATAMIENTO PARA ESTUDIO CON ECO RENOVESICAL Y EVENTUAL DERIVACION A ESPECIALIDAD SI CORRESPONDE.
- PENDIENTE RESULTADOS DE UROCULTIVO, RESCATAR EN SU CESFAM EN 48H
- ACUDIR AL SERVICIO DE URGENCIA ANTE SIGNOS DE ALARMA (PERSISTENCIA DE FIEBRE MAS DE 48H DESDE INICIADO EL ANTIBIOTICO, DESHIDRATACION O SOS)`
    },
    
    {
        id: 28,
        titulo: "PIELONEFRITIS AGUDA",
        tipo: "urgencia",
        contenido: `- REPOSO RELATIVO
- ABUNDANTE LIQUIDO
- CIPROFLOXACINO/CEFADROXILO/COTRIMOXAZOL FORTE 800/100 CADA 12 H POR 7-10 DIAS
- DOLOSPAM 1 COMP CADA 8H POR 3 DIAS
- NO BEBER LIQUIDO QUE IRRITE LA VEJIGA: ALCOHOL, CAFE, TE.
- MEDIDAS DE HIGIENE (SE EDUCA. USO DE ROPA INTERIOR DE ALGODON, EVITAR LA HUMEDAD.
- CONTROL EN SU CESFAM CON RESULTADO DE UROCULTIVO EN 48H
- CONTROL EN URGENCIAS EN CASO DE: FIEBRE, DOLOR DE ESPALDA, VOMITOS O EN CASO NECESARIO`
    },
    
    {
        id: 29,
        titulo: "ESCABIOSIS",
        tipo: "urgencia",
        contenido: `- TRATAMIENTO DEBE REALIZARLO TODA LA FAMILIA!!!
- ACUDIR A CESFAM PARA SOLICITAR TRATAMIENTO
- ADULTO: DELTAMETRINA (0.02 O LAUNOL LOCIÓN) O PERMETRINA AL 5% LOCIÓN O VASELINA AZUFRADA AL 10% APLICAR DURANTE 3 NOCHES CONSECUTIVAS, DESDE EL CUELLO HACIA ABAJO, BAÑO MATINAL AL OTRO DIA, DESCANSAR 4 DÍAS Y LUEGO REPETIR 3 NOCHES MAS.
- NIÑOS: VASELINA AZUFRADA AL 6% APLICAR DURANTE 3 NOCHES CONSECUTIVAS, DESDE EL CUELLO HACIA ABAJO, BAÑO MATINAL AL OTRO DIA, DESCANSAR 4 DÍAS Y LUEGO REPETIR 3 NOCHES MAS.
-  LAVADO DE ROPA, ROPA DE CAMA Y TOALLAS CON AGUA CALIENTE REMOJAR 1 HRA. LO QUE NO SE PUEDA LAVAR SE PLANCHA.
- LOS OBJETOS MAS GRANDES SE PUEDEN GUARDAR EN BOLSAS PLÁSTICAS SELLADAS POR 10 DIAS
- EXPONER FRAZADAS Y CUBRECAMAS AL AIRE Y SOL POR TODO UN DIA.
- URGENCIAS EN CASO DE: INFECCIÓN DE HERIDAS, FIEBRE O SOS.
- CONTROL EN SU CESFAM EN CASO NECESARIO.`
    },
    
    {
        id: 30,
        titulo: "CONJUNTIVITIS",
        tipo: "urgencia",
        contenido: `- ASEO OCULAR FRECUENTE
- NO TOCAR LOS OJOS CON MANOS SUCIAS
- CLORANFENICOL COLIRIO APLICAR 2 GOTAS CADA 6 HRS EN CADA OJO POR 7 DÍAS
- CLORANFENICOL UNGÜENTO APLICAR POR LAS NOCHES POR 7 DIAS
- CLORFENAMINA 4 MG 1 COMP CADA 12 H POR 3 DÍAS.
- CONTROL SOS EN CASO DE PERSISTENCIA DEL CUADRO EN SU CESFAM RESPECTIVO`
    },
    
    {
        id: 31,
        titulo: "PARÁLISIS FACIAL",
        tipo: "urgencia",
        contenido: `- REPOSO EN CASA.
- HIDRATACION ABUNDANTE
- CONTROL EN CESFAM PARA EVALUACION POR KINESIOLOGIA.
- PARACETAMOL 500MG 2 COMP CADA 12 HRS POR 5 DIAS
- NAPROXENO 550MG 1 COMP CADA 12 HRS POR 3 DAS
- PREDNISONA 20MG 1 Y 1/2 COMP CADA 12 HRS POR 5 DIAS
- CICLOBENZAPRINA 10 MG ½ COMP CADA NOCHE POR 5 NOCHES.
- LAGRIMAS ARTIFICIALES 2 GOTAS CADA 2-4 HORAS O SEGUN NECESIDAD
- EXTRASISTEMA PARA ACORTAR TIEMPO DE ENFERMEDAD: VALACICLOVIR 1000MG. 1 COMPRIMDO CADA 8 HRS POR 7 DIAS`
    },

    {
        id: 32,
        titulo: "MASTITIS",
        tipo: "urgencia",
        contenido: `- REPOSO RELATIVO
- NO SUSPENDER LACTANCIA MATERNA, EXTRACCION LECHE CADA 2 HRS.
- USO DE SOSTEN AJUSTADO PARA EVITAR LA SUSPENSION MAMARIA Y EL DOLOR.
- IBUPROFENO 400 MG 1 COMP CADA 8H POR 3 DIAS.
- CLOXACILINA 500 MG 1 COMP CADA 6H POR 7 DIAS.
- COMPRESAS TIBIAS EN MAMA DOLOROSA PARA FAVORECER DRENAJE.
- URGENCIAS EN CASO DE FIEBRE , DOLOR QUE NO CEDE O SOS.`
    },
    
    {
        id: 33,
        titulo: "HERIDA MENOR",
        tipo: "urgencia",
        contenido: `- REPOSO RELATIVO
- NO MOJAR HERIDA, MANTENER APÓSITO
- CURACIONES DIA POR MEDIO EN SU CESFAM.
- IBUPROFENO 400 MG 1 COMP CADA 8H POR 3 DIAS.
- URGENCIAS SOS.`
    },
    
    {
        id: 34,
        titulo: "DERMATITIS DEL PAÑAL",
        tipo: "urgencia",
        contenido: `- MUDA DE PAÑAL FRECUENTE
- PASTA LASSAR EN CADA MUDA
- CLOTRIMAZOL 1% APLICAR EN REGION DEL PAÑAL EN CADA MUDA O CADA 6H POR 7 DIAS.
- URGENCIAS SOS: HERIDAS QUE EMPEORAN SECRECION O SOS.`
    },
    
    {
        id: 35,
        titulo: "CÓLICO BILIAR",
        tipo: "urgencia",
        contenido: `- REPOSO RELATIVO
- REGIMEN LIVIANO, EVITAR CONSUMO DE FRITURAS, PASTELES, HARINAS REFINADAS, CARNES O LO QUE IDENTIFIQUE COMO GATILLANTE DEL DOLOR.
- DOLOSPAM 1 COMP CADA 8H POR 3 DIAS.
- DICLOFENACO 50 MG 1 COMP CADA 8H POR 3 DIAS.
- DOMPERIDONA 10 MG 1 COMP CADA 8H POR 3 DIAS.
- URGENCIAS EN CASO DE: PERSISTENCIA DE DOLOR, ORINA OSCURA, COLORACION AMARILLA DE PIEL, FIEBRE O EN CASO NECESARIO.`
    },
    
    {
        id: 36,
        titulo: "CEFALEA",
        tipo: "urgencia",
        contenido: `- REPOSO RELATIVO, EVITAR RUIDOS Y LUCES MOLESTAS
- ABUNDANTE HIDRATACION, AL MENOS 2 LTRS DE LIQUIDOS AL DIA.
- NAPROXENO 550 MG 1 COMP SOS MAX CADA 12 H POR 3 DIAS.
- DOMPERIDONA 10 MG 1 COMP CADA 8H POR 3 DIAS.
- URGENCIAS EN CASO DE SÍNTOMAS DE ALARMA: EL PEOR DOLOR DE CABEZA DE SU VIDA, COMPROMISO DE CONCIENCIA, DOLOR QUE EMPEORA, NAUSEAS O VÓMITOS EXPLOSIVOS O EN CASO NECESARIO.`
    },

    {
        id: 37,
        titulo: "CANDIDIASIS VAGINAL",
        tipo: "urgencia",
        contenido: `- NO USAR JABONES EN ZONA GENITAL, TAMPOCO JABONES INTIMOS, ASEO SOLO CON AGUA.
- CLOTRIMAZOL OVULO 500 MG 1 UNIDA VIA VAGINAL EN LA NOCHE POR UNA VEZ.
- CLOTRIMAZOL CREMA APLICAR EN LABIOS Y REGION EXTERNA DE LA VULVA CADA 8H POR 5 DIAS.
- CONTROL CON SU MATRONA EN CASO DE PERSISTENCIA DE LOS SINTOMAS.`
    },
    
    {
        id: 38,
        titulo: "CANDIDIASIS ORAL",
        tipo: "urgencia",
        contenido: `- RÉGIMEN HABITUAL
- HERVIR POR 20 MINUTOS CUALQUIER ELEMENTO EN CONTACTO CON LA BOCA. SE PUEDE USAR PARA DESINFECTAR 3⁄4 DE TASA DE CLORO EN 4 LITROS DE AGUA, PARA DESINFECTAR SUPERFICIES.
- NISTATINA 20 GOTAS (100.000 UI) EN ALGODÓN O GASA. PASAR POR BOCA 4 VECES AL DÍA POR 7-10 DÍAS.
- AL DISMINUIR LESIONES, CAMBIAR CHUPONES DE MAMADERA.
- EN CASO DE QUE TOME PECHO: MADRE TAMBIÉN DEBE SER TRATADA, NISTATINA 20 GOTAS EN ALGODÓN Y APLICAR LUEGO DE CADA MAMADA. POR 7-10 DÍAS. DEBE USAR SOSTÉN LIMPIO TODOS LOS DÍAS.`
    },
    
    {
        id: 39,
        titulo: "CONSTIPACIÓN CRÓNICA",
        tipo: "urgencia",
        contenido: `INDICACIONES:
- SE REALIZA EDUCACION SOBRE ENTRENAMIENTO DEL INTESTINO: ACUDIR AL BAÑO 5-10 MIN POSTERIOR A COMER, SENTARSE EN POSICIÓN CÓMODA. CON AMBOS PIES APOYADOS EN EL SUELO
- MANTENER ALTO CONSUMO DE FIBRA: FRUTAS CON CASCARA, ENSALADAS VERDES, LEGUMBRES.
- EVITAR ALIMENTOS QUE GENEREN CONSTIPACIÓN: CHOCOLATE, MANZANA SIN CASCARA, BEBIDAS COLA, QUESO, PLATANO.
- BEBER ABUNDANTES LIQUIDOS.

DESIMPACTACION:
- PEG 1-1,5 G/KG/DIA (SE PUEDE DIVIDIR EN DOS DOSIS AL DIA) MANTENER ESTA DOSIS POR 3 DIAS A 1 SEMANA- (DOSIS MAX 100 GR X DIA)
- PREPARACION; PEG 3350 1 SOBRE DE 17 GRAMOS EN 240 CC DE AGUA.
- ENEMA DE FOSFATO: UN FLEET DE ADULTO TRAE 133 ML. (NO USAR EN MENORES DE 2 AÑOS, NI FALLA RENAL NI CARDIÓPATA) >2 AÑOS: 2- 5 ML POR KG MAX 133 ML
- PROCTOCLISIS CON SF TIBIO; 15-20 CC/KG (MAX 500) + 2 AMP DE BICARBONATO + 1 AMP DE VASELINA LIQUIDA A PASAR EN 2-4 HRS
- LACTANTE<6M: SUPOSITORIO DE GLICERINA O ESTIMULACIÓN RECTAL CON SONDA

MANTENIMIENTO POSTERIOR A MANEJO DE DESIMPACTACION:
- PEG 3350 DOSIS 0,5 A 1 MG/KG/DIA
- PEG SIN ELECTROLITOS (PEG4000) USAR EN MAYORES DE 6M
- PEG CON ELECTROLITOS (PEG3350) USAR EN MAYORES DE 2 A
- LACTULOSA 1.3 CC KG EN 1 A 2 DOSIS.(RAM COLICOS)
- JARABE DE MALTA 1-3 CC/KG EN 1 A 2 DOSIS.`
    },
    
    {
        id: 40,
        titulo: "VÉRTIGO",
        tipo: "urgencia",
        contenido: `- HIDRATACION ABUNDANTE
- SE REALIZA EDUCACION RESPECTO A VERTIGO
- DIFENIDOL 25 MG (COMPRAR EN EXTRASISTEMA) 1 COMPRIMIDO CADA 4 HORAS, DURANTE EL TIEMPO QUE SEA NECESARIO (MÁXIMO 7 DIAS CONSECUTIVOS)
- CONTROL SOS EN SU CESFAM RESPECTIVO`
    },
    
    {
        id: 41,
        titulo: "MORDEDURA DE PERRO",
        tipo: "urgencia",
        contenido: `- REPOSO EN CASA
- NO MOJAR HERIDA
- CURACIÓN DE HERIDA EN 48 HRS
- AMOXICILINA/CLAVULANICO 875/125MG, 1 CADA 12 HRS POR 7 DIAS
- IBUPROFENO 200MG/5ML, 7.5 CC CADA 8 HRS POR DOS DIAS
- PARACETAMOL 500MG, 1 SOS MAX CADA 8 HRS
- RETIRO DE PUNTOS EN 10 EN SU CENTRO ASISTIR A URGENCIA EN CASO SOS`
    },

    {
        id: 42,
        titulo: "ABUSO SEXUAL",
        tipo: "urgencia",
        contenido: `OPCIÓN 1:
TAR POR UN MES:
- AZT 100MG C/12 HRS JARABE
- LAMIVUDINA 60MG C/12 HRS JARABE
- RALTEGRAVIR 100MG C/12 HRS VO PAPELILLO
ATB:
- CEFTRIAXONA 1.5 GR IM POR UNA VEZ-AZITROMICINA 200MG/5ML, 6 CC VO POR UNA VEZ
- METRONIDAZOL 125MG/5ML, 2.4 CC CADA 8 HRS POR 7 DIAS

OPCIÓN 2:
- REPOSO EN CASA
- CONTINUAR CON INVESTIGACIÓN
- CONTROL EN POLICLINICO DE INFECTOLOGIA INFANTIL
- GESTIONAR AL PRESTADOR PARA CONTINUIDAD DE ATENCION DE VVS
- AZT 100MG C/12 HRS JARABE POR UN MES
- LAMIVUDINA 60MG C/12 HRS JARABE POR UN MES
- RALTEGRAVIR 100MG C/12 HRS VO PAPELILLO POR UN MES
- METRONIDAZOL 125MG/5ML, 2.4 CC CADA 8 HRS POR 7 DIAS`
    },
    
    {
        id: 43,
        titulo: "BALANITIS",
        tipo: "urgencia",
        contenido: `- REPOSO EN CASA
- REGIMEN HABITUAL, ABUNDANTE LIQUIDO
- PARACETAMOL 100MG/ML, 54 GTS SOS MAX CADA 8 HRS
- IBUPROFENO 200MG/5ML, 4.5CC CADA 8 HRS POR 2 DIAS, LUEGO SOS
- UNGÜENTO CAF CADA 8 HRS POR 7 DIAS
- ASEO GENITAL FRECUENTE SOLO CON AGUA
- CONTROL CON MEDICO EN SU CENTRO EN 48-72HRS
- ASISTIR A URGENCIA EN CASO SOS, SE EXPLICAN SINTOMAS`
    },
    
    {
        id: 44,
        titulo: "PARALISIS FACIAL PERIFERICA",
        tipo: "urgencia",
        contenido: `- REPOSO POR 72 HRS PARA VIGILANCIA EN DOMICILIO.
- CONTROL LUNES 10.06.2024 EN SU CESFAM RESPECTIVO PARA DERIVACION A
- MANEJO KINESIOLOGICO MOTOR
- HIDRATACION ABUNDANTE
- PARACETAMOL 500MG 2 COMP CADA 12 HRS POR 5 DIAS
- NAPROXENO 550MG 1 COMP CADA 12 HRS POR 5 DIAS
- PREDNISONA 20MG 1 Y 1/2 COMP CADA 12 HRS POR 5 DIAS
- PROTECCION OCULAR CON LAGRIMAS ARTIFICIALES (HIPROMELOSA 0,7%) 2
- GOTAS CADA 2-4 HORAS O SEGUN NECESIDAD
- EXTRASISTEMA PARA ACORTAR TIEMPO DE ENFERMEDAD:

-  $7.000 CAJA 35 COMP: ACICLOVIR 400MG CADA 4HORAS POR 7 DíAS. SALTAR DOSIS NOCTURNA. RECOMIENDO HORARIOS: 6AM - 10AM - 14PM - 18PM - 22PM - SALTAR DOSIS DE LAS 2 AM PARA LUEGO REPETIR A LAS 6AM.
-  CONTROL CON KINESIOLOGIA EN 72H PARA INICIAR REHABILITACION NERVIO FACIAL. SE ENTREGA HOJA DE EJERCICIOS.`
    },
    
    {
        id: 45,
        titulo: "DOLOR DENTAL",
        tipo: "urgencia",
        contenido: `- REGIMEN BLANDO
- ACUDIR A CESFAM A PEDIR HORA PARA URGENCIA DENTAL PARA EVALUACION
- AMOXICILINA/AC CLAVULANICO 875/125 MG 1 COMP CADA 12 H POR 7 DIAS.DICLOFENACO 50 MG 1 COMP CADA 8H POR 3 DIAS.
- PARACETAMOL 500MG 2 COMP CADA 8H POR 3 DIAS.
- URGENCIAS SOS: FIEBRE, DOLOR QUE EMPEORA, SECRECION O SOS.`
    },
    
    {
        id: 46,
        titulo: "DESGARRO MUSCULAR NO TRAUMATICO",
        tipo: "urgencia",
        contenido: `- REPOSO EN CASA
- HIDRATACIÓN ABUNDANTE
- PARACETAMOL 500 MG 2 COMPRIMIDOS SOS, MAX CADA 6 HRS
- IBUPROFENO 400 MG 1 COMPRIMIDO CADA 8 HRS POR 3 DIAS
- FRIO LOCAL INDIRECTO 15.20 MIN 3 VECES AL DIA LOS PRIMEROS 3 DIAS DESDE INICIADO EL CUADRO, LUEGO CALOR TIBIO LOCAL
- CONTROL EN SU CESFAM
- URGENCIAS SOS EN CASO DE AUMENTO DE VOLUMEN DE EXTREMIDAD, DOLOR INTENSO, IMPOTENCIA FUNCIONAL, DIFICULTAD RESPIRATORIA O CUALQUIER DETERIORO CLINICO`
    },

    {
        id: 47,
        titulo: "OXIURIASIS",
        tipo: "urgencia",
        contenido: `- TRATAMIENTO CORRESPONDE A CESFAM.
- UÑAS CORTAS Y LAVADO DE MANOS FRECUENTE, ESCOBILLAR DEBAJO DE LAS UÑAS, BAÑO DIARIO Y ASEO GENITAL DIARIO.
- LAVADO DE ROPA DE CAMA Y DE VESTIR CON AGUA CALIENTE O PLANCHAR.
- LIMPIEZA DE SUPERFICIES.
- EN CASO DE MOLESTIA GENITAL PASTA LASSAR O CUALQUIER CREMA CON OXIDO DE ZINC.
- SI INFLAMACION IMPORTENTE PERIANAL: HIDROCORTISONA.
- MEBENDAZOL 100 A 200 MG POR DOSIS POR 1 VEZ Y LUEGO REPETIR A LOS 15 DIAS.
- DEBE RECIBIR TRATAMIENTO TODA LA FAMILIA.
- SE SUGIERE USO DE PROBIÓTICOS.`
    },
    
    {
        id: 48,
        titulo: "INDICACIONES ALTA CIRUGÍA",
        tipo: "urgencia",
        contenido: `- REGIMEN HABITUAL
- REPOSO RELATIVO
- HIDRATACIÓN ORAL ABUNDANTE
- PARACETAMOL 500 MG. 2 COMPRIMIDOS CADA 8 HRS VIA ORAL POR 5 DIAS
- KETOPROFENO 50 MG.  1 COMPRIMIDO CADA 8 HRS VIA ORAL POR 3 DIAS (SOS)
- METOCLOPRAMIDA 10 MG. 1 COMPRIMIDO CADA 12 HRS VIA ORAL POR 3 DIAS
- MANTENER CONTROLES Y TRATAMIENTO DE PATOLOGIAS CRONICAS
- CONTROL CON MEDICO EN SU CONSULTORIO EN UNA SEMANA
- CONSULTAR EN URGENCIAS EN CASO DE SINTOMAS/SIGNOS DE ALARMA: SE EXPLICAN A PACIENTE`
    },
    
    {
        id: 49,
        titulo: "HOSPITALIZAR CIRUGÍA/PABELLÓN",
        tipo: "urgencia",
        contenido: `- HOSPITALIZAR EN CIRUGIA CUIDADOS MEDIOS
- REGIMEN CERO
- REPOSO RELATIVO
- SF 0.9% A 80-100 CC/HR
- HGT PRECOMIDAS + INSULINA CRISTALINA SEGUN ESQUEMA (> 180 mg/dl).
- CEFTRIAXONA 2 GR DIA EV
- METRONIDAZOL 500 MG CADA 8 HRS EV
- PARACETAMOL 1 GR CADA 8 HRS EV
- KETOPROFENO 100 MG CADA 8 HRS EV
- DIPIRONA 1 GR CADA 8 HRS EV
- OMEPRAZOL 40 MG DIA EV
- ONDANSETRON 4 MG CADA 8 HRS EV SOS
- CSV CADA 6 HRS 
- PREPARAR PARA PABELLON
- PENDIENTE EVALUACIÓN POR CIRUGIA “INSERTAR SUBESPECIALIDAD”`
    },
    
    {
        id: 50,
        titulo: "HOSPITALIZAR APENDICITIS",
        tipo: "urgencia",
        contenido: `- HOSPITALIZAR EN CIRUGIA PEDIATRICA
- REPOSO RELATIVO
- REGIMEN CERO
- SF 0.9% A 70 CC/HR
- CEFTRIAXONA 2 GR DIA EV
- METRONIDAZOL 500 MG CADA 8 HRS EV
- AMIKACINA 700 MG CADA 24 HRS EV
- AMPICILINA 2 GR CADA 6 HRS EV
- KETOPROFENO 100 MG CADA 8 HRS EV-PARACETAMOL 500 MG CADA 8 HRS EV
- CSV CADA 6 HRS Y EVALUAR DOLOR
- PREPARAR PARA PABELLON
- CONTROL SOS POR CIRUJANO`
    },
    
    {
        id: 51,
        titulo: "QUEMADOS CIRUGÍA",
        tipo: "urgencia",
        contenido: `- REPOSO EN CASA
- ABUNDANTE LIQUIDO
- NO MOJAR HERIDA
- NO ASISTIR A JARDIN POR ESTA Y LA OTRA SEMANA
- PARACETAMOL 36 GTS CADA 8 HRS POR 3 DIAS
- IBUPROFENO 200MG/5ML, 3 CC SOS MAX CADA 8 HRS
- CONTROL CON ENFERMERA EL XX-XX-2025 A LAS 09.00 HRS EN POLI QUEMADOS, MODULO A, CDT HHHA
- ASISTIR A URGENCIA EN CASO SOS`
    },

    {
        id: 52,
        titulo: "HOSPITALIZAR QUEMADOS",
        tipo: "urgencia",
        contenido: `- HOSPITALIZAR EN CIRUGIA PEDIATRICA
- REPOSO RELATIVO
- REGIMEN COMUN
- SF 20 CC/HORA
- KETOPROFENO 50 MG CADA 8 HRS EV
- PARACETAMOL 750 MG CADA 8 HRS EV
- CURACION CON TELFA EN 48 HRS POR ENFERMERA EN MANOS
- APLICAR UNGÜENTO CAF EN REGION FACIAL CADA 6 HRS, MANTENER DESCUBIERTA-CSV CADA 6 HRS Y EVALUAR DOLOR
- RESCATAR PCR PACIENTE Y ACOMPAÑANTE
- CONTROL MAÑANA CON EQUIPO DE QUEMADOS
- CONTROL CON CIRUJANO EN CASO SOS`
    },
    
    {
        id: 53,
        titulo: "ILEITIS",
        tipo: "urgencia",
        contenido: `- REPOSO EN CASA POR ESTA SEMANA
- REGIMEN LIVIANO, TODO COCIDO, EVITAR LACTEOS POR UNA SEMANA
- PARACETAMOL 100MG/ML, 42 GTS SOS MAX CADA 8 HRS
- IBUPROFENO 200MG/5ML, 3.7 CC CADA 8 HRS POR 4 DIAS, LUEGO SOS
- PROBIOTICOS, 1 CADA 12 HRS POR 5 DIAS
- SRO60, 300 CC FRACCIONADO POR EVENTO, SEA VOMITO O DIARREA
- CONTROL CON MEDICO EN SU CENTRO EN 48-72HRS
- ASISTIR A URGENCIA EN CASO SOS, SE EXPLICAN SINTOMA`
    },
    
    {
        id: 54,
        titulo: "CORTE PEQUEÑO CON HISTOCRYL",
        tipo: "urgencia",
        contenido: `- REPOSO EN CASA
- REGIMEN LIVIANO
- REPOSO DEPORTIVO POR UNA SEMANA
- NO MOJAR HERIDA AL MENOS POR 5 DIAS, SE LE CAERÁ COSTRA
- PARACETAMOL 100MG/ML, GTS SOS MAX CADA 8 HRS
- IBUPROFENO 200MG/5ML, CC CADA 8 HRS POR 2 DIAS, LUEGO SOS
- CONTROL CON MEDICO EN SU CENTRO EN 48 HRS
- ASISTIR A URGENCIA EN CASO SOS, SE EXPLICAN SINTOMAS`
    },
    
    {
        id: 55,
        titulo: "TORSION DE HIDATIDE DE MORGANI",
        tipo: "urgencia",
        contenido: `- REPOSO EN CASA-NO ASISTIR AL COLEGIO POR ESTA SEMANA Y REPOSO DEPORTIVO POR ESTA SEMANA
- REGIMEN HABITUAL
- PARACETAMOL 100MG/ML, 75 GTS CADA 8 HRS POR 3 DIAS, LUEGO SOS MAX CADA 8 HRS
- IBUPROFENO 200MG/5ML, X CC CADA 8 HRS POR 3 DIAS, LUEGO SOS
- FRIO LOCAL
- USO DE ROPA INTERIOR AJUSTADA TIPO SLIP, CON BUEN ELASTICO AL MENOS POR 3 DIAS
- CONTROL CON MEDICO EN SU CENTRO EN 48-72HRS
- ASISTIR A URGENCIA EN CASO SOS, SE EXPLICAN SINTOMAS`
    },
    
    {
        id: 56,
        titulo: "ARTROSIS CADERA / RODILLA PARA CONTROL APS",
        tipo: "urgencia",
        contenido: `- REPOSO RELATIVO
- PARACETAMOL 500 MG. 1 COMPRIMIDOS CADA 8 HORAS VÍA ORAL POR 5 DÍAS.tobi
- PARACETAMOL / TRAMADOL 325 / 37.5 MG 1 COMPRIMIDO CADA 8 HORAS VÍA ORAL POR 5 DÍAS
- DICLOFENACO 50 MG. 1 COMPRIMIDO CADA 8 HORAS VÍA ORAL POR 3 DÍAS
- CONTROL CON MÉDICO GENERAL EN SU CONSULTORIO EN 3-4 SEMANAS PARA MANEJO INTEGRAL DE ARTROSIS (EVALUACIÓN NUTRICIONAL, EMPA, KTM)
- CONSULTAR EN URGENCIAS DE SU CONSULTORIO. SE EXPLICAN SIGNOS DE ALERTA`
    },
    
    {
        id: 57,
        titulo: "HERIDA COMPLEJA",
        tipo: "urgencia",
        contenido: `- REPOSO RELATIVO.
- CELECOXIB 200 MG 1 COMP CADA 12 HORAS VÍA ORAL POR 3 DÍAS.
- PARACETAMOL 500 MG. 2 COMPRIMIDOS CADA 8 HORAS VÍA ORAL POR 5 DÍAS.
- CEFADROXILO 500 MG. 1 COMPRIMIDO CADA 12 HORAS VÍA ORAL POR 5 DÍAS.
- CURACIONES CADA 2-3 DÍAS EN CONSULTORIO DE ORIGEN
- RETIRO DE PUNTOS EN 10-14 DÍAS EN CONSULTORIO DE ORIGEN.
- COMPLETAR ESQUEMA DE VACUNACIÓN ANTITETÁNICA.
- CONTROL S.O.S CON MÉDICO EN SU CONSULTORIO`
    },

    {
        id: 58,
        titulo: "CONTUSIÓN",
        tipo: "urgencia",
        contenido: `- REPOSO RELATIVO. 
- FRÍO LOCAL 10-15 MIN 3 VECES AL DÍA POR DÍAS
- CELECOXIB  200 MG. 1 COMPRIMIDO CADA 12 HORAS VÍA ORAL POR 5 DÍAS.
- PARACETAMOL 500 MG. 2 COMPRIMIDOS CADA 8 HORAS VÍA ORAL POR 5 DÍAS.
- CONSULTAR EN URGENCIAS S.O.S. SE EXPLICAN SIGNOS DE ALERTA.`
    },

    {
        id: 59,
        titulo: "TENDINITIS",
        tipo: "urgencia",
        contenido: `- REPOSO RELATIVO. EVITAR MOVIMIENTOS BRUSCOS Y LEVANTAR OBJETOS PESADOS.pie
- FRÍO LOCAL 10-15 MIN 3 VECES AL DIA POR 5 DÍAS
- CELECOXIB 200 MG. 1 COMPRIMIDO CADA 12 HORAS VÍA ORAL POR 3 DÍAS.
- PARACETAMOL 500 MG. 2 COMPRIMIDOS CADA 8 HORAS VÍA ORAL POR 5 DÍAS.
- CONTROL MÉDICO EN 2 SEMANAS EN CONSULTORIO DE ORIGEN PARA EVALUACIÓN CLÍNICA.
- CONSULTAR EN URGENCIAS S.O.S. SE EXPLICAN SIGNOS DE ALERTA.`
    },

    {
        id: 60,
        titulo: "INGRESO FRACTURA EXPUESTA.",
        tipo: "urgencia",
        contenido: `- RÉGIMEN CERO.
- REPOSO RELATIVO.
- CONTROL DE SIGNOS VITALES CADA 8 HORAS.- SUERO FISIOLÓGICO A 60 CC/HORA.
- CEFAZOLINA 1 GRAMO CADA 8 HORAS VÍA ENDOVENOSA.
- GENTAMICINA 160 MG AL DÍA POR VÍA ENDOVENOSA.
- PENICILINA SÓDICA 5.000.000 UI CADA 6 HORAS VÍA ENDOVENOSA.
- DIPIRONA 1 GRAMO CADA 8 HORAS VÍA ENDOVENOSA.
- TRAMADOL 100 MG CADA 8 HORAS VÍA ENDOVENOSA.
- ONDANSETRON 4 MG S.O.S. VÍA ENDOVENOSA.
- MEDIAS ANTITROMBÓTICAS.
- MEDIDAS PREVENTIVAS DE ÚLCERAS POR PRESIÓN.
- COMPLETAR ESQUEMA DE VACUNACIÓN ANTITETÁNICA.
- EXÁMENES PREOPERATORIOS . CONSENTIMIENTO INFORMADO OK.
- PENDIENTE PABELLÓN POR SUA`
    },
    
    {
        id: 61,
        titulo: "INGRESO FRACTURA NO EXPUESTA PARA TUTORPIERNA",
        tipo: "urgencia",
        contenido: `- RÉGIMEN CERO. PIE PIERNA EN ALTO.
- REPOSO RELATIVO.
- CONTROL DE SIGNOS VITALES CADA 8 HORAS.
- SUERO FISIOLÓGICO A 60 CC/HORA.
- DIPIRONA 1 GRAMO CADA 8 HORAS VÍA ENDOVENOSA.
- TRAMADOL 100 MG CADA 8 HORAS VÍA ENDOVENOSA.
- ONDANSETRON 4 MG S.O.S. VÍA ENDOVENOSA.
- MEDIAS ANTITROMBÓTICAS.
- MEDIDAS PREVENTIVAS DE ÚLCERAS POR PRESIÓN.
-EXÁMENES PREOPERATORIOS . TOMADOS EN S.U.A. CONSENTIMIENTO INFORMADO OK.
- PENDIENTE PABELLÓN POR SUA`
    },
    
    {
        id: 62,
        titulo: "FRACTURA CERRADA PARA OBSERVACIÓN PARTES BLANDAS:",
        tipo: "urgencia",
        contenido: `- RÉGIMEN LIVIANO. PIE PIERNA EN ALTO.
- REPOSO RELATIVO.
- CONTROL DE SIGNOS VITALES CADA 8 HORAS.
- PARACETAMOL 500 MG 2 COMP CADA 8 HORAS VIA ORAL
- DIPIRONA 1 GRAMO CADA 8 HORAS VÍA ENDOVENOSA.
- TRAMADOL 100 MG CADA 8 HORAS VÍA ENDOVENOSA. S.O.S
- ONDANSETRON 4 MG S.O.S. VÍA ENDOVENOSA. S.O.S
- ENOXAPARINA 40MG AL DIA SC
- MEDIAS ANTITROMBÓTICAS.
- MEDIDAS PREVENTIVAS DE ÚLCERAS POR PRESIÓN.
- EVALUACIÓN DE PARTES BLANDAS POR TRAUMATÓLOGO MAÑANA `
    },

    {
        id: 63,
        titulo: "INFECCIÓN PERIPROTÉSICA/ ARTRITIS SÉPTICA",
        tipo: "urgencia",
        contenido: `- RÉGIMEN CERO.
- REPOSO RELATIVO
- CONTROL DE SIGNOS VITALES CADA 8 HORAS.
- SUERO FISIOLÓGICO A 60 CC/HORA.
- DIPIRONA 1 GRAMO CADA 8 HORAS VÍA ENDOVENOSA.
- TRAMADOL 100 MG CADA 8 HORAS VÍA ENDOVENOSA.
- ONDANSETRON 4 MG S.O.S. VÍA ENDOVENOSA.
- MEDIAS ANTITROMBÓTICAS.
- MEDIDAS PREVENTIVAS DE ÚLCERAS POR PRESIÓN.
- EXÁMENES PREOPERATORIOS ( HEMOCULTIVOS PERIFÉRICOS X 2 Y URC) TOMADOS EN S.U.A. CONSENTIMIENTO INFORMADO OK.
- PENDIENTE PABELLÓN POR SUA`
    },

    {
        id: 64,
        titulo: "LESIÓN PUNTA DEDO PARA VSO (PRIMERA ATENCIÓN)",
        tipo: "urgencia",
        contenido: `PRIMERA ATENCIÓN
- REPOSO RELATIVO, NO UTILIZAR MANO AFECTADA- MANO EN ALTO
- DICLOFENACO 50 MG 1 COMPRIMIDO 8 HORAS VÍA ORAL POR 3 DÍAS.
- PARACETAMOL 2 COMPRIMIDO CADA 8 HORAS VÍA ORAL POR 5 DÍAS.
- CEFADROXILO 500 MG. 1 COMPRIMIDO CADA 12 HORAS VÍA ORAL POR 5 DÍAS.
- CONTROL EN 6 DÍAS EN SERVICIO DE URGENCIAS HHHA TRAUMATOLOGIA CON A LAS PARA EVALUACIÓN CLÍNICA
- PRECAUCIONES VENDAJE SEMIOCLUSIVO:
    1) NO RETIRAR VENDAJE
    2) VENDAJE PUEDE TOMAR MAL OLOR, NO IMPLICA INFECCIÓN.
    3) EN CASO DE RETIRO DE SEMIOCLUSIVO O ALGUNA COMPLICACIÓN CONSULTAR EN URGENCIA TRAUMATOLÓGICA HHHA.

CONTROLES POSTERIORES
- REPOSO RELATIVO
- MANO EN ALTO . 
- ANALGESIA S.O.S
- CONTROL EN 2 SEMANA EN SERVICIO DE URGENCIAS _____ CON DRA LUNA A LAS 17:00HRS
- PRECAUCIONES VENDAJE SEMIOCLUSIVO:
    4) NO RETIRAR VENDAJE
    5) VENDAJE PUEDE TOMAR MAL OLOR, NO IMPLICA INFECCIÓN.
    6) EN CASO DE RETIRO DE SEMIOCLUSIVO O ALGUNA COMPLICACIÓN CONSULTAR EN URGENCIA TRAUMATOLÓGICA HHHA`
    },

    {
        id: 65,
        titulo: "AMPUTACIÓN TRAUMÁTICA DEDO CON FRACTURA MALLET FINGER",
        tipo: "urgencia",
        contenido: `- REPOSO RELATIVO. USO DE FÉRULA DE INMOVILIZACIÓN EN EXTENSIÓN DURANTE 8 SEMANAS (ESTRICTO DIA-NOCHE). NO LEVANTAR OBJETOS PESADOS CON MANO AFECTADA.
- CELECOXIB 200 MG. 1 COMPRIMIDO CADA 12 HORAS VÍA ORAL POR 3 DÍAS.
- PARACETAMOL 500 MG. 2 COMPRIMIDOS CADA 8 HORAS VÍA ORAL POR 5 DÍAS.
- CONTROL EN POLICLÍNICO DE TRAUMATOLOGÍA HHHA EN 2 SEMANAS (MÓDULO D DEL CDT) EQUIPO DE MANO.luxacion
- CONSULTAR EN URGENCIAS S.O.S. SE EXPLICAN SIGNOS DE ALERTA.`
    },
    
    {
        id: 66,
        titulo: "LUXACIÓN FALANGE",
        tipo: "urgencia",
        contenido: `- REPOSO RELATIVO.
- USO DE FÉRULA DIGITAL
- NO LEVANTAR OBJETOS PESADOS CON MANO AFECTADA.
- NO MOVILIZAR DEDO AFECTADO.
- CELECOXIB 200 MG. 1 COMPRIMIDO CADA 12 HORAS VÍA ORAL POR 3 DÍAS.
- PARACETAMOL 500 MG. 2 COMPRIMIDOS CADA 8 HORAS VÍA ORAL POR 5 DÍAS.
- CONTROL EN POLICLÍNICO DE TRAUMATOLOGÍA HHHA EN 10 DIAS POLIBECADOS CON RX DE CONTROL 
- CONTROL S.O.S SUA TMT`
    },
    
    {
        id: 67,
        titulo: "ESGUINCE INTERFALÁNGICO",
        tipo: "urgencia",
        contenido: `- REPOSO RELATIVO. 
- USO DE VENDAJE SOLIDARIO X 3 DIAS
- NO LEVANTAR OBJETOS PESADOS CON MANO AFECTADA.
- NO MOVILIZAR DEDO AFECTADO.
- REPOSO DEPORTIVO x1 SEMANA
- DICLOFENACO 50MG 1 COMPRIMIDO CADA 8 HORAS VÍA ORAL POR 3 DÍAS.
- PARACETAMOL 500 MG. 2 COMPRIMIDOS CADA 8 HORAS VÍA ORAL POR 3 DÍAS.
- CONTROL EN SU CONSULTORIO SOS
- CONTROL S.O.S SUA`
    },

    {
        id: 68,
        titulo: "SINDROME DE TUNEL CARPIANO ",
        tipo: "urgencia",
        contenido: `- REPOSO RELATIVO. EVITAR LEVANTAR OBJETOS PESADOS. NO REALIZAR MOVIMIENTOS MUÑECAREPETITIVOS.
- INMOVILIZADOR DE MUÑECA EN LAS NOCHES
- FRÍO LOCAL.
- CELECOXIB 200 MG. 1 COMPRIMIDO CADA 12 HORAS VÍA ORAL POR 3 DÍAS.
- PARACETAMOL 500 MG. 2 COMPRIMIDOS CADA 8 HORAS VÍA ORAL POR 5 DÍAS.
- CICLOBENZAPRINA 10 MG. 1 COMPRIMIDO POR NOCHE VÍA ORAL POR 3 DÍAS.
- KINESIOTERAPIA MOTORA EN CONSULTORIO DE ORIGEN.
- CONTROL MÉDICO EN CONSULTORIO DE ORIGEN EN 2 SEMANAS.
- CONSULTAR EN URGENCIAS S.O.S. SE EXPLICAN SIGNOS DE ALERTA.`
    },

    {
        id: 69,
        titulo: "FRACTURA DE MUÑECA QUIRÚRGICA",
        tipo: "urgencia",
        contenido: `- REPOSO RELATIVO.
- USO DE YESO BRAQUICARPIANO Y CABESTRILLO. 
- PARACETAMOL 500 MG. 2 COMPRIMIDOS CADA 8 HORAS VÍA ORAL POR 5 DÍAS.
- CELECOXIB 200 MG. 1 COMPRIMIDO CADA 12 HORAS VÍA ORAL POR 5 DÍAS
- SE INGRESA A LISTA DE ESPERA QUIRÚRGICA PARA RESOLUCIÓN DEFINITIVA, ESPERAR LLAMADO DE UNIDAD PREIRÚRGICO HHHA.
- EN CASO DE NO SER CONTACTQUADO EN 10 DÍAS, CONSULTAR EN UNIDAD PRE QUIRÚRGICA POR CIRUGÍA.
- CONSULTAR EN URGENCIAS S.O.S. SE EXPLICAN SIGNOS DE ALERTA.`
    },

    {
        id: 70,
        titulo: "FRACTURA DE MUÑECA ORTOPÉDICA",
        tipo: "urgencia",
        contenido: `- REPOSO RELATIVO.
- USO DE YESO Y CABESTRILLO. 
- NO LEVANTAR OBJETOS PESADOS CON MANO AFECTADA.
- NO MOJAR NI RETIRAR YESO
- REPOSO DEPORTIVO
- CELECOXIB 200 MG. 1 COMPRIMIDO CADA 12 HORAS VÍA ORAL POR 5 DÍAS.
- PARACETAMOL 500 MG. 2 COMPRIMIDOS CADA 8 HORAS VÍA ORAL POR 5 DÍAS
- CONTROL EN POLICLÍNICO DE TRAUMATOLOGÍA HHHA EN 7 A 10 DÍAS (MÓDULO D DEL CDT) CON CONTROL RADIOLÓGICO (SE ENTREGA ORDEN DE RX)
- CONSULTAR EN URGENCIAS S.O.S. SE EXPLICAN SIGNOS DE ALERTA`
    },
    
    {
        id: 71,
        titulo: "FRACTURA DIAFISIARIA METACARPIANOS ORTOPÉDICA",
        tipo: "urgencia",
        contenido: `- USO DE VALVA INTRÍNSECO PLUS Y CABESTRILLO. 
- NO LEVANTAR OBJETOS PESADOS CON MANO AFECTADA.
- NO MOJAR NI RETIRAR YESO
- REPOSO DEPORTIVO
- CELECOXIB 200 MG. 1 COMPRIMIDO CADA 12 HORAS`
    },
    
    {
        id: 72,
        titulo: "FRACTURA DE QUINTO METACARPIANO",
        tipo: "urgencia",
        contenido: `- REPOSO RELATIVO.
- USO DE VALVA EN INTRÍNSECO PLUS
- NO LEVANTAR OBJETOS PESADOS CON MANO AFECTADA.
- NO MOJAR NI RETIRAR YESO
- REPOSO DEPORTIVO
- CELECOXIB 200 MG. 1 COMPRIMIDO CADA 12 HORAS VÍA ORAL POR 5 DÍAS.
- PARACETAMOL 500 MG. 2 COMPRIMIDOS CADA 8 HORAS VÍA ORAL POR 5 DÍASfalange
- CONTROL EN POLICLÍNICO DE TRAUMATOLOGÍA HHHA  EN 2 SEMANAS (MÓDULO D DEL CDT) CON CONTROL RADIOLÓGICO (SE ENTREGA ORDEN DE RX).
- CONSULTAR EN URGENCIAS S.O.S. SE EXPLICAN SIGNOS DE ALERTA`
    },

    {
        id: 73,
        titulo: "FRACTURA DE ESCAFOIDES ORTOPÉDICA",
        tipo: "urgencia",
        contenido: `- REPOSO RELATIVO.
- USO DE YESO ANTEBRAQUIOPALMAR Y CABESTRILLO. 
- NO LEVANTAR OBJETOS PESADOS CON MANO AFECTADA.
- NO MOJAR NI RETIRAR YESO
- REPOSO DEPORTIVO
- CELECOXIB 200 MG. 1 COMPRIMIDO CADA 12 HORAS VÍA ORAL POR 5 DÍAS.
- PARACETAMOL 500 MG. 2 COMPRIMIDOS CADA 8 HORAS VÍA ORAL POR 5 DÍAS
- CONTROL EN POLICLÍNICO DE TRAUMATOLOGÍA HHHA EN 2 SEMANAS (MÓDULO D DEL CDT) CON CONTROL RADIOLÓGICO (SE ENTREGA ORDEN DE RX).
- CONSULTAR EN URGENCIAS S.O.S. SE EXPLICAN SIGNOS DE ALERTA`
    },

    {
        id: 74,
        titulo: "FRACTURA DE ESCAFOIDES QUIRÚRGICA",
        tipo: "urgencia",
        contenido: `- REPOSO RELATIVO.
- USO DE YESO ANTEBRAQUIOPALMAR Y CABESTRILLO. 
- NO LEVANTAR OBJETOS PESADOS CON MANO AFECTADA.
- NO MOJAR NI RETIRAR YESO
- REPOSO DEPORTIVO
- CELECOXIB 200 MG. 1 COMPRIMIDO CADA 12 HORAS VÍA ORAL POR 5 DÍAS.
- PARACETAMOL 500 MG. 2 COMPRIMIDOS CADA 8 HORAS VÍA ORAL POR 5 DÍAS
 - SE INGRESA A LISTA DE ESPERA QUIRÚRGICA PARA RESOLUCIÓN DEFINITIVA, ESPERAR LLAMADO DE UNIDAD PREQUIRÚRGICO HHHA.
- EN CASO DE NO SER CONTACTADO EN 10 DÍAS, CONSULTAR EN UNIDAD PRE QUIRÚRGICA POR CIRUGÍA.
- CONSULTAR EN URGENCIAS S.O.S. SE EXPLICAN SIGNOS DE ALERTA.`
    },

    {
        id: 75,
        titulo: "FRACTURA FALANGE ORTOPÉDICA",
        tipo: "urgencia",
        contenido: `- REPOSO RELATIVO.
- USO DE FERULA INMOVILIZADORA
- NO LEVANTAR OBJETOS PESADOS CON MANO AFECTADA.
- NO MOJAR NI RETIRAR YESO
- REPOSO DEPORTIVO
- CELECOXIB 200 MG. 1 COMPRIMIDO CADA 12 HORAS VÍA ORAL POR 5 DÍAS.
- PARACETAMOL 500 MG. 2 COMPRIMIDOS CADA 8 HORAS VÍA ORAL POR 5 DÍAS
- CONTROL EN POLICLÍNICO DE TRAUMATOLOGÍA HHHA  EN 2 SEMANAS (MÓDULO D DEL CDT) CON CONTROL RADIOLÓGICO (SE ENTREGA ORDEN DE RX).
- CONSULTAR EN URGENCIAS S.O.S. SE EXPLICAN SIGNOS DE ALERTA FRACTURA`
    },
    
    {
        id: 76,
        titulo: "FRACTURA FALANGE QUIRÚRGICA",
        tipo: "urgencia",
        contenido: `- REPOSO RELATIVO.
- USO DE FÉRULA INMOVILIZADORA
- NO LEVANTAR OBJETOS PESADOS CON MANO AFECTADA.
- NO MOJAR NI RETIRAR YESO
- REPOSO DEPORTIVO
- CELECOXIB 200 MG. 1 COMPRIMIDO CADA 12 HORAS VÍA ORAL POR 5 DÍAS.
- PARACETAMOL 500 MG. 2 COMPRIMIDOS CADA 8 HORAS VÍA ORAL POR 5 DÍAS
 - SE INGRESA A LISTA DE ESPERA QUIRÚRGICA PARA RESOLUCIÓN DEFINITIVA, ESPERAR LLAMADO DE UNIDAD PREQUIRÚRGICO HHHA.
- EN CASO DE NO SER CONTACTADO EN 10 DÍAS, CONSULTAR EN UNIDAD PRE QUIRÚRGICA POR CIRUGÍA.
- CONSULTAR EN URGENCIAS S.O.S. SE EXPLICAN SIGNOS DE ALERTA`
    },
    
    {
        id: 77,
        titulo: "FRACTURA OLECRANON QUIRÚRGICA",
        tipo: "urgencia",
        contenido: `- REPOSO RELATIVO.
- USO DE YESO BRAQUICARPIANO Y CABESTRILLO. 
- NO LEVANTAR OBJETOS PESADOS CON MANO AFECTADA.
- NO MOJAR NI RETIRAR YESO
- CELECOXIB 200 MG 1 COMPRIMIDO CADA 12 HORAS VÍA ORAL POR 5 DÍAS.
- PARACETAMOL 500 MG. 2 COMPRIMIDOS CADA 8 HORAS VÍA ORAL POR 5 DÍAS
- SE INGRESA A LISTA DE ESPERA QUIRÚRGICA PARA RESOLUCIÓN DEFINITIVA, ESPERAR LLAMADO DE UNIDAD PREQUIRÚRGICO HHHA.
- EN CASO DE NO SER CONTACTADO EN 10 DÍAS, CONSULTAR EN UNIDAD PRE QUIRÚRGICA POR CIRUGÍA.
- CONSULTAR EN URGENCIAS S.O.S. SE EXPLICAN SIGNOS DE ALERTA.`
    },

    {
        id: 78,
        titulo: "FRACTURA DE ULNA DIAFISIARIA AISLADA ORTOPÉDICA",
        tipo: "urgencia",
        contenido: `- REPOSO RELATIVO.
- USO DE YESO BRAQUICARPIANO Y CABESTRILLO. 
- NO LEVANTAR OBJETOS PESADOS CON MANO AFECTADA.
- NO MOJAR NI RETIRAR YESO
- REPOSO DEPORTIVO
- CELECOXIB 200 MG. 1 COMPRIMIDO CADA 12 HORAS VÍA ORAL POR 5 DÍAS.
- PARACETAMOL 500 MG. 2 COMPRIMIDOS CADA 8 HORAS VÍA ORAL POR 5 DÍAS
- CONTROL EN POLICLÍNICO DE TRAUMATOLOGÍA HHHA EN 2 SEMANAS (MÓDULO D DEL CDT) CON CONTROL RADIOLÓGICO (SE ENTREGA ORDEN DE RX)
- CONSULTAR EN URGENCIAS S.O.S. SE EXPLICAN SIGNOS DE ALERTA`
    },
    
    {
        id: 79,
        titulo: "FRACTURA CUPULA RADIAL ORTOPÉDICA (MASON I-II SIN BLOQUEO)",
        tipo: "urgencia",
        contenido: `- REPOSO RELATIVO.
- USO DE CABESTRILLO. 
- EVITAR PRONO SUPINACIÓN CON EXTREMIDAD AFECTADA X 1 SEMANA.
- CELECOXIB 200 MG. 1 COMPRIMIDO CADA 12 HORAS VÍA ORAL POR 5 DÍAS.
- PARACETAMOL 500 MG. 2 COMPRIMIDOS CADA 8 HORAS VÍA ORAL POR 5 DÍAS
- CONTROL EN POLICLÍNICO DE TRAUMATOLOGÍA HHHA EN 2 SEMANAS (MÓDULO D DEL CDT) CON CONTROL RADIOLÓGICO (SE ENTREGA ORDEN DE RX)
- CONSULTAR EN URGENCIAS S.O.S. SE EXPLICAN SIGNOS DE ALERTA`
    },
    
    {
        id: 80,
        titulo: "LESIÓN TENDÓN EXTENSOR MANO",
        tipo: "urgencia",
        contenido: `- REPOSO RELATIVO. 
- USO DE PALMETA DE YESO
- NO LEVANTAR OBJETOS PESADOS CON MANO AFECTADA.
- NO MOJAR NI RETIRAR YESO
- NO MOVILIZAR DEDO AFECTADO.
- DICLOFENACO 50 MG. 1 COMPRIMIDO CADA 8 HORAS VÍA ORAL POR 3 DÍAS.
- PARACETAMOL 500 MG. 2 COMPRIMIDOS CADA 8 HORAS VÍA ORAL POR 5 DÍAS.LUXACI
- CEFADROXILO 500 MG. 1 COMPRIMIDO CADA 12 HORAS VÍA ORAL POR 5 DÍAS.
- CONTROL EN 2 SEMANAS EN CDT MÓDULO D POLI BECADOS TMT, SACAR HORA.
- SACAR HORA CONTROL CON TERAPEUTA OCUPACIONAL PARA INICIO PROTOCOLO REHABILITACIÓN EN SERVICIO MEDICINA FISICA Y REHABILITACION (EDIFICIO VIEJO 2DO PISO)
- CONTROL S.O.S SUA TMT`
    },
    
    {
        id: 81,
        titulo: "LESIÓN TENDÓN FLEXOR MANO (PENDIENTE POR RESOLVER)",
        tipo: "urgencia",
        contenido: `- REPOSO RELATIVO.
- DICLOFENACO 50 MG 1 COMP CADA 12 HORAS V?A ORAL POR 3 DIAS.
- PARACETAMOL 500 MG. 2 COMPRIMIDOS CADA 8 HORAS V?A ORAL POR 5 DIAS.
- CEFADROXILO 500 MG. 1 COMPRIMIDO CADA 12 HORAS V?A ORAL POR 7 DIAS.
- SE INGRESA A LISTA DE ESPERA QUIRÚRGICA HHHA - COMPLETAR ESQUEMA DE VACUNACION ANTITETANICA.
- CONTROL S.O.S CON M?DICO EN SU CONSULTORIO`
    },

    {
        id: 82,
        titulo: "LESIÓN MENISCAL AGUDA",
        tipo: "urgencia",
        contenido: `- REPOSO RELATIVO. EVITAR ACTIVIDAD DEPORTIVA HASTA CONTROL POR ESPECIALISTA.
- FRÍO LOCAL INTERMITENTE 
- PARACETAMOL 500 MG. 2 COMPRIMIDOS CADA 8 HORAS VÍA ORAL POR 5 DÍAS.
- CELECOXIB 200 MG. 1 COMPRIMIDO CADA 12 HORAS VÍA ORAL POR 3 DÍAS.
- CONTROL EN POLICLÍNICO DE TRAUMATOLOGÍA (MÓDULO D. CDT). EQUIPO DE RODILLA. CON RESULTADOS DE RESONANCIA MAGNÉTICA DE RODILLA (SE ENTREGA ORDEN PARA GESTIÓN AMBULATORIA)
- CONSULTAR EN URGENCIAS S.O.S. SE EXPLICAN SIGNOS DE ALERTA.`
    },
    
    {
        id: 83,
        titulo: "LESIÓN DE CRUZADO ANTERIOR",
        tipo: "urgencia",
        contenido: `- REPOSO RELATIVO. EVITAR ACTIVIDAD DEPORTIVA HASTA CONTROL POR ESPECIALISTA.
- FRÍO LOCAL INTERMITENTE 
- PARACETAMOL 500 MG. 2 COMPRIMIDOS CADA 8 HORAS VÍA ORAL POR 5 DÍAS.
- CELECOXIB 200 MG. 1 COMPRIMIDO CADA 12 HORAS VÍA ORAL POR 3 DÍAS.
- CONTROL EN POLICLÍNICO DE TRAUMATOLOGÍA (MÓDULO D. CDT). EQUIPO DE RODILLA. CON RESULTADOS DE RESONANCIA MAGNÉTICA DE RODILLA ( SE ENTREGA ORDEN PARA GESTIÓN AMBULATORIA)
- CONSULTAR EN URGENCIAS S.O.S. SE EXPLICAN SIGNOS DE ALERTA.`
    },
    
    {
        id: 84,
        titulo: "LUXACIÓN DE PATELA / INESTABILIDAD PATELAR AGUDA CON FACTORES DE RIESGO:",
        tipo: "urgencia",
        contenido: `- REPOSO RELATIVO. USO DE INMOVILIZADOR DE RODILLA.
- PARACETAMOL 500 MG. 2 COMPRIMIDOS CADA 8 HORAS VÍA ORAL POR 5 DÍAS.
- CELECOXIB 200 MG. 1 COMPRIMIDO CADA 12 HORAS VÍA ORAL POR 3 DÍAS.
- CONTROL EN POLICLÍNICO DE TRAUMATOLOGIA (MODULO D. CDT) EN 2 SEMANAS. EQUIPO DE RODILLA.
- CONSULTAR EN URGENCIAS S.O.S. SE EXPLICAN SIGNOS DE ALERTA.`
    },
    
    {
        id: 85,
        titulo: "LUXACIÓN DE PATELA / INESTABILIDAD PATELAR AGUDA SIN FACTORES DE RIESGO :",
        tipo: "urgencia",
        contenido: `- REPOSO RELATIVO. USO DE INMOVILIZADOR DE RODILLA POR 2 SEMANAS
- PARACETAMOL 500 MG. 2 COMPRIMIDOS CADA 8 HORAS VÍA ORAL POR 5 DÍAS.
- CELECOXIB 200 MG. 1 COMPRIMIDO CADA 12 HORAS VÍA ORAL POR 3 DÍAS.
- FRIO LOCAL 4-5 VECES AL DIA POR 5 DÍAS. MAXIMO 20 MINUTOS POR SESION
-SOLICITAR KNT EN SU CENTRO, ÉNFASIS EN FORTALECIMIENTO DE CUADRICEPS (BASTO MEDIAL OBLICUO) Y CADENA CINÉTICA PROXIMAL, INCLUYE GLÚTEOS, ISQUIOTIBIALES Y ROTADORES DE CADERA. 
- CONSULTAR EN URGENCIAS S.O.S. SE EXPLICAN SIGNOS DE ALERTA.`
    },
    
    {
        id: 86,
        titulo: "ROTURA DE TENDÓN  PATELAR",
        tipo: "urgencia",
        contenido: `- REPOSO RELATIVO. USO DE INMOVILIZADOR DE RODILLA.
- PARACETAMOL 500 MG. 2 COMPRIMIDOS CADA 8 HORAS VÍA ORAL POR 5 DÍAS.
- CELECOXIB 200 MG. 1 COMPRIMIDO CADA 12 HORAS VÍA ORAL POR 3 DÍAS.
- SE INGRESA A LEQ
- CONTROL EN POLICLÍNICO DE TRAUMATOLOGIA (MODULO D. CDT) EN 2 SEMANAS. EQUIPO DE RODILLA.
- CONSULTAR EN URGENCIAS S.O.S. SE EXPLICAN SIGNOS DE ALERTA.`
    },

    {
        id: 87,
        titulo: "LESIÓN EXTENSOR PIE",
        tipo: "urgencia",
        contenido: `- REPOSO RELATIVO. 
- USO DE VALVA EN EXTENSIÓN DE ORTEJO
- NO PISAR
- NO MOJAR NI RETIRAR YESO
- DICLOFENACO 50 MG 1 COMP CADA 8 HORAS VÍA ORAL POR 3 DÍAS.
- PARACETAMOL 500 MG. 2 COMPRIMIDOS CADA 8 HORAS VÍA ORAL POR 5 DÍAS.
- CEFADROXILO 500 MG. 1 COMPRIMIDO CADA 12 HORAS VÍA ORAL POR 5 DÍAS.
- CONTROL CON TRAUMATOLOGO EN 10-14 DÍAS EN HOSPITAL DE ORIGEN (SOLICITAR HORA EN MÓDULO D CDT)
- SACAR HORA CONTROL CON TERAPEUTA OCUPACIONAL HOSPITAL DE ORIGEN PARA INICIO PROTOCOLO REHABILITACIÓN EN SERVICIO MEDICINA FISICA Y REHABILITACION (EDIFICIO VIEJO 2DO PISO) Y CONFECCIÓN DE ORTESIS DE TERMOPLÁSTICO
- CONTROL S.O.S SUA TMT`
    },
    
    {
        id: 88,
        titulo: "ESGUINCE TOBILLO GRADO 2-3",
        tipo: "urgencia",
        contenido: `- REPOSO RELATIVO
- FRIO LOCAL 15 MIN, 4 VECES AL DIA X 3 DIAS
- BOTA ORTOPEDICA X 3 -5 DÍAS
- PARACETAMOL 500 MG. 2 COMPRIMIDOS CADA 8 HORAS VÍA ORAL POR 5 DÍAS.
- CELECOXIB  200 MG. 1 COMPRIMIDO CADA 12 HORAS VÍA ORAL POR 5 DÍAS.
- KNT MOTORA EN CESFAM CORRESPONDIENTE 10 SESIONES, 2 - 3 VECES POR SEMANA
- CONTROL EN CESFAM PARA OBSERVAR EVOLUCIÓN
- CONTROL S.O.S SERVICIO URGENCIA. SE EXPLICAN SIGNOS DE ALERTA`
    },
    
    {
        id: 89,
        titulo: "ROTURA AGUDA TENDÓN DE AQUILES",
        tipo: "urgencia",
        contenido: `- REPOSO PIE PIERNA EN ALTO
- BOTA ORTOPEDICA EN EQUINO
- BOTA DE YESO EN EQUINO
- DEAMBULAR CON 2 BASTONES.
- PARACETAMOL 500 MG. 2 COMPRIMIDOS CADA 8 HORAS VÍA ORAL POR 5 DÍAS.
- CELECOXIB  200 MG. 1 COMPRIMIDO CADA 12 HORAS VÍA ORAL POR 5 DÍAS.
- INGRESO LISTA ESPERA QUIRÚRGICA
- SI NO ES LLAMADO PARA CIRUGÍA EN 2 SEMANAS, ACUDIR A UNIDAD DE PREQUIRÚRGICO.
- CONTROL S.O.S SERVICIO URGENCIA - SE EXPLICAN SIGNOS DE ALERTA`
    },

    {
        id: 90,
        titulo: "FRACTURA DE 5 MTT:",
        tipo: "urgencia",
        contenido: `- REPOSO PIE-PIERNA EN ALTO
- USO DE BOTA ORTOPEDICA- ZAPATO ORTOPÉDICO
- DEAMBULAR CON 2 BASTONES. 
- PARACETAMOL 500 MG. 2 COMPRIMIDOS CADA 8 HORAS VÍA ORAL POR 5 DÍAS.
- CELECOXIB 200 MG . 1 COMPRIMIDO CADA 12 HORAS VÍA ORAL POR 5 DÍAS.
- CONTROL EN POLICLÍNICO DE TRAUMATOLOGÍA HHHA (POLI CHOQUE) EN 2 SEMANAS (MÓDULO D DEL CDT) CON CONTROL RADIOLÓGICO (SE ENTREGA ORDEN DE RX).
- CONSULTAR EN URGENCIAS S.O.S. SE EXPLICAN SIGNOS DE ALERTA.`
    },

    {
        id: 91,
        titulo: "FRACTURA TOBILLO ORTOPEDICA",
        tipo: "urgencia",
        contenido: `- REPOSO PIE-PIERNA EN ALTO
- USO DE BOTA DE YESO ABIERTA- BOTA ORTOPEDICA. 
- DEAMBULAR CON 2 BASTONES. 
- NO APOYAR PIE FRACTURADO
- CUIDADOS YESO: NO MOJAR, NO GOLPEAR, NO RETIRAR
- PARACETAMOL 500 MG. 2 COMPRIMIDOS CADA 8 HORAS VÍA ORAL POR 5 DÍAS.
- CELECOXIB 200 MG . 1 COMPRIMIDO CADA 12 HORAS VÍA ORAL POR 5 DÍAS.
- CONTROL EN POLICLÍNICO DE TRAUMATOLOGÍA HHHA (POLI CHOQUE) EN 2 SEMANAS (MÓDULO D DEL CDT) CON CONTROL RADIOLÓGICO (SE ENTREGA ORDEN DE RX).
- CONSULTAR EN URGENCIAS S.O.S. SE EXPLICAN SIGNOS DE ALERTA.`
    },

    {
        id: 92,
        titulo: "FRACTURA TOBILLO QUIRÚRGICA:",
        tipo: "urgencia",
        contenido: `- REPOSO PIE-PIERNA EN ALTO
- NO APOYAR PIE FRACTURADO
- USO DE BOTA DE YESO ABIERTA. 
- DEAMBULAR CON 2 BASTONES. 
- CUIDADOS YESO: NO MOJAR, NO GOLPEAR, NO RETIRAR
- PARACETAMOL 500 MG. 2 COMPRIMIDOS CADA 8 HORAS VÍA ORAL POR 5 DÍAS.
- CELECOXIB 200 MG . 1 COMPRIMIDO CADA 12 HORAS VÍA ORAL POR 5 DÍAS.
- SE INGRESA A LISTA DE ESPERA QUIRÚRGICA PARA RESOLUCIÓN DEFINITIVA, ESPERAR LLAMADO DE UNIDAD PREQUIRÚRGICO HHHA.
- EN CASO DE NO SER CONTACTADO EN 10 DÍAS, CONSULTAR EN UNIDAD PRE QUIRÚRGICA POR CIRUGÍA.
- CONSULTAR EN URGENCIAS S.O.S. SE EXPLICAN SIGNOS DE ALERTA`
    },
    
    {
        id: 93,
        titulo: "FRACTURA ORTEJO",
        tipo: "urgencia",
        contenido: `- REPOSO RELATIVO. PIE EN ALTO. USO DE VENDAJE SOLIDARIO. USO DE CALZADO CÓMODO Y AMPLIO. NO UTILIZAR TACOS.
- CELECOXIB 200 MG. 1 COMPRIMIDO CADA 12 HORAS VÍA ORAL POR 3 DÍAS.
- PARACETAMOL 500 MG. 2 COMPRIMIDOS CADA 8 HORAS VÍA ORAL POR 5 DÍAS.
- CONTROL MÉDICO EN CONSULTORIO DE ORIGEN EN 3 SEMANAS PARA EVALUACIÓN CLÍNICA Y CONTROL RADIOLÓGICO.
- CONSULTAR EN URGENCIAS S.O.S. SE EXPLICAN SIGNOS DE ALERTA.`
    },
    
    {
        id: 94,
        titulo: "FASCITIS PLANTAR",
        tipo: "urgencia",
        contenido: `- REPOSO RELATIVO. EVITAR ACTIVIDAD DEPORTIVA POR 2 SEMANAS.
- SE SUGIERE USO TALONERA SILICONA
- PARACETAMOL 500 MG, 2 CADA 8 HORAS V.O POR 5 DÍAS
- CELECOXIB  200 MG. 1 COMPRIMIDO CADA 12 HORAS VÍA ORAL POR 5 DÍAS.
- KINESIOTERAPIA EJERCICIOS ELONGACIÓN PLANTAR ( SE ENTREGA ORDEN)
- SE ENTREGA GUIA DE EJERCICIOS PARA DOMICILIO
- CONTROL S.O.S EN SU CONSULTORIO`
    },

    {
        id: 95,
        titulo: "HOMBRO DOLOROSO / SÍNDROME MANGUITO ROTADOR",
        tipo: "urgencia",
        contenido: `- REPOSO RELATIVO. EVITAR LEVANTAR OBJETOS PESADOS. NO REALIZAR MOVIMIENTOS REPETITIVOS.
- FRÍO LOCAL.
- CELECOXIB 200 MG. 1 COMPRIMIDO CADA 12 HORAS VÍA ORAL POR 3 DÍAS.
- PARACETAMOL 500 MG. 2 COMPRIMIDOS CADA 8 HORAS VÍA ORAL POR 5 DÍAS.
- CICLOBENZAPRINA 10 MG. 1 COMPRIMIDO POR NOCHE VÍA ORAL POR 3 DÍAS.
- KINESIOTERAPIA MOTORA EN CONSULTORIO DE ORIGEN.
- CONTROL MÉDICO EN CONSULTORIO DE ORIGEN EN 3 SEMANAS.
- CONSULTAR EN URGENCIAS APS  S.O.S. SE EXPLICAN SIGNOS DE ALERTA.`
    },

    {
        id: 96,
        titulo: "CERVICOBRAQUIALGIA",
        tipo: "urgencia",
        contenido: `- REPOSO RELATIVO. EVITAR LEVANTAR OBJETOS PESADOS. NO REALIZAR MOVIMIENTOS REPETITIVOS.
- CALOR LOCAL.
- CELECOXIB 200 MG. 1 COMPRIMIDO CADA 12 HORAS VÍA ORAL POR 3 DÍAS.
- PARACETAMOL 500 MG. 2 COMPRIMIDOS CADA 8 HORAS VÍA ORAL POR 5 DÍAS.
- CICLOBENZAPRINA 10 MG. 1 COMPRIMIDO POR NOCHE VIA ORAL POR 3 DIAS.
- PREGABALINA 75 MG EN LA NOCHE POR 30 DÍAS
- SE SOLICITA RM DE COLUMNA CERVICAL PARA ESTUDIO AMBULATORIO, CON RESULTADO SOLICITAR HORA DE CONTROL EN POLICLINICO DE TRAUMATOLOGIA DE COLUMNA HHHA TMT ( MODULO D CDT)???
- CONSULTAR EN URGENCIAS S.O.S. SE EXPLICAN SIGNOS DE ALERTA.`
    },

    {
        id: 97,
        titulo: "FRACTURA DE TUBEROSIDAD MAYOR DEL HÚMERO",
        tipo: "urgencia",
        contenido: `- REPOSO RELATIVO.
- USO DE INMOVILIZADOR CON COJIN DE ABDUCCION.
- NO LEVANTAR OBJETOS PESADOS CON MANO AFECTADA.
- REPOSO DEPORTIVO
- CELECOXIB. 1 COMPRIMIDO CADA 12 HORAS VÍA ORAL POR 3 DÍAS.
- PARACETAMOL 500 MG. 2 COMPRIMIDOS CADA 8 HORAS VÍA ORAL POR 5 DÍAS
- CONTROL EN POLICLÍNICO DE TRAUMATOLOGÍA DE HOMBRO HHHA EN 1 SEMANA (MÓDULO D DEL CDTf) CON CONTROL RADIOLÓGICO (SE ENTREGA ORDEN DE RX).
- CONSULTAR EN URGENCIAS S.O.S. SE EXPLICAN SIGNOS DE ALERTA.`
    },
    
    {
        id: 98,
        titulo: "FRACTURA HUMERO PROXIMAL ORTOPÉDICA",
        tipo: "urgencia",
        contenido: `- REPOSO RELATIVO.
- USO DE INMOVILIZADOR DE HOMBRO/ CABESTRILLO SIMPLE 
- NO LEVANTAR OBJETOS PESADOS CON MANO AFECTADA.
- REPOSO DEPORTIVO
- CELECOXIB. 1 COMPRIMIDO CADA 12 HORAS VÍA ORAL POR 3 DÍAS.
- PARACETAMOL 500 MG. 2 COMPRIMIDOS CADA 8 HORAS VÍA ORAL POR 5 DÍAS
- CONTROL EN POLICLÍNICO DE TRAUMATOLOGÍA DE HOMBRO HHHA EN 1 SEMANA (MÓDULO D DEL CDT) CON CONTROL RADIOLÓGICO (SE ENTREGA ORDEN DE RX).
- CONSULTAR EN URGENCIAS S.O.S. SE EXPLICAN SIGNOS DE ALERTA.`
    },
    
    {
        id: 99,
        titulo: "FRACTURA HUMERO PROXIMAL QUIRÚRGICA",
        tipo: "urgencia",
        contenido: `- REPOSO RELATIVO.
- USO DE INMOVILIZADOR DE HOMBRO/ CABESTRILLO SIMPLE 
- NO LEVANTAR OBJETOS PESADOS CON MANO AFECTADA.
- REPOSO DEPORTIVO
- CELECOXIB. 1 COMPRIMIDO CADA 12 HORAS VÍA ORAL POR 5 DÍAS.
- PARACETAMOL/TRAMADOL 1 COMPRIMIDOS CADA 8 HORAS VÍA ORAL POR 10 DÍAS
- SE INGRESA A LISTA DE ESPERA QUIRÚRGICA PARA RESOLUCIÓN DEFINITIVA, ESPERAR LLAMADO DE UNIDAD PREQUIRÚRGICO HHHA.
- EN CASO DE NO SER CONTACTADO EN 10 DÍAS, CONSULTAR EN UNIDAD PRE QUIRÚRGICA POR CIRUGÍA.
- CONSULTAR EN URGENCIAS S.O.S. SE EXPLICAN SIGNOS DE ALERTA.`
    },

    {
        id: 100,
        titulo: "FRACTURA DIAFISIARIA DE HUMERO QUIRÚRGICA",
        tipo: "urgencia",
        contenido: `- REPOSO RELATIVO.
- USO DE CABESTRILLO. 
- CELECOXIB 200 MG. 1 COMPRIMIDO CADA 12 HORAS VÍA ORAL POR 3 DÍAS.
- PARACETAMOL 500 MG. 2 COMPRIMIDOS CADA 8 HORAS VÍA ORAL POR 5 DÍAS.
- SE INGRESA A LISTA DE ESPERA QUIRÚRGICA PARA RESOLUCIÓN DEFINITIVA, ESPERAR LLAMADO DE UNIDAD PREQUIRÚRGICO HHHA.
- EN CASO DE NO SER CONTACTADO EN 10 DÍAS, CONSULTAR EN UNIDAD PRE QUIRÚRGICA POR CIRUGÍA.
- CONSULTAR EN URGENCIAS S.O.S. SE EXPLICAN SIGNOS DE ALERTA.`
    },

    {
        id: 101,
        titulo: "LUXACION ACROMIOCLAVICULAR",
        tipo: "urgencia",
        contenido: `- REPOSO RELATIVO.
- USO DE CABESTRILLO. 
- NO LEVANTAR OBJETOS PESADOS CON MANO AFECTADA.
- CELECOXIB  200 MG. 1 COMPRIMIDO CADA 12 HORAS VÍA ORAL POR 5 DÍAS.
- PARACETAMOL 500 MG. 2 COMPRIMIDOS CADA 8 HORAS VÍA ORAL POR 5 DÍAS
- INGRESO LISTA DE ESPERA QUIRÚRGICA
- CONTROL EN UNIDAD PREQUIRÚRGICA HHHA EN 2 SEMANAS EN CASO DE NO SER LLAMADO PARA CIRUGÍA
- CONSULTAR EN URGENCIAS S.O.S. SE EXPLICAN SIGNOS DE ALERTA.`
    },

    {
        id: 102,
        titulo: "LUXACIÓN DE HOMBRO",
        tipo: "urgencia",
        contenido: `- REPOSO RELATIVO. 
- USO CABESTRILLO POR 3 SEMANAS
- USO DE CABESTRILLO POR 10 DÍAS LUEGO SOLO USO NOCTURNO
- INICIAR EJERCICIOS PENDULARES SUAVES EN 1 SEMANA (SE EXPLICA A LA PACIENTE).
- DICLOFENACO 50 MG. 1 COMPRIMIDO CADA 8 HORAS VÍA ORAL POR 3 DÍAS.
- PARACETAMOL 500 MG. 2 COMPRIMIDOS CADA 8 HORAS VÍA ORAL POR 5 DÍAS.
- CONTROL EN POLICLÍNICO DE TRAUMATOLOGÍA HHHA EN 3 SEMANAS (MÓDULO D DEL CDT). EQUIPO DE HOMBRO.
- CONSULTAR EN URGENCIAS S.O.S. SE EXPLICAN SIGNOS DE ALERTA`
    },
    
    {
        id: 103,
        titulo: "FRACTURA DE CLAVÍCULA ORTOPÉDICA",
        tipo: "urgencia",
        contenido: `- REPOSO RELATIVO. USO DE CABESTRILLO. 
- CELECOXIB 200 MG. 1 COMPRIMIDO CADA 12 HORAS VÍA ORAL POR 3 DÍAS.
- PARACETAMOL 500 MG. 2 COMPRIMIDOS CADA 8 HORAS VÍA ORAL POR 5 DÍAS.
- CONTROL EN POLICLÍNICO DE TRAUMATOLOGÍA HHHA EN 3 SEMANAS (MÓDULO D DEL CDT). EQUIPO DE HOMBRO. SE ENTREGA ORDEN DE RADIOGRAFÍA.
- CONSULTAR EN URGENCIAS S.O.S. SE EXPLICAN SIGNOS DE ALERTA.`
    },
    
    {
        id: 104,
        titulo: "FRACTURA DE CLAVÍCULA QUIRÚRGICA",
        tipo: "urgencia",
        contenido: `- REPOSO RELATIVO. USO DE CABESTRILLO. 
- CELECOXIB 200 MG. 1 COMPRIMIDO CADA 12 HORAS VÍA ORAL POR 3 DÍAS.
- PARACETAMOL 500 MG. 2 COMPRIMIDOS CADA 8 HORAS VÍA ORAL POR 5 DÍAS.
- SE INGRESA A LISTA DE ESPERA QUIRÚRGICA PARA RESOLUCIÓN DEFINITIVA, ESPERAR LLAMADO DE UNIDAD PREQUIRÚRGICO HHHA.
- EN CASO DE NO SER CONTACTADO EN 10 DÍAS, CONSULTAR EN UNIDAD PRE QUIRÚRGICA POR CIRUGÍA.
- CONSULTAR EN URGENCIAS S.O.S. SE EXPLICAN SIGNOS DE ALERTA.`
    },

    {
        id: 105,
        titulo: "SÍNDROME LUMBOCIÁTICO AGUDO",
        tipo: "urgencia",
        contenido: `- REPOSO RELATIVO. EVITAR LEVANTAR OBJETOS PESADOS. NO REALIZAR MOVIMIENTOS REPETITIVOS.
- CALOR LOCAL.
- CELECOXIB 200 MG. 1 COMPRIMIDO CADA 12 HORAS VÍA ORAL POR 3 DÍAS.
- PARACETAMOL 500 MG. 2 COMPRIMIDOS CADA 8 HORAS VÍA ORAL POR 5 DÍAS.
- CICLOBENZAPRINA 10 MG. 1 COMPRIMIDO POR NOCHE VIA ORAL POR 3 DIAS.
- KINESIOTERAPIA MOTORA EN CONSULTORIO DE ORIGEN.
  - EJERCICIOS FORTALECIMIENTO CORE
  - FISIOTERAPIA
- CONTROL MÉDICO EN CONSULTORIO DE ORIGEN EN 2 SEMANAS.
- CONSULTAR EN URGENCIAS S.O.S. SE EXPLICAN SIGNOS DE ALERTA.`
    },

    {
        id: 106,
        titulo: "FRACTURA COXIS",
        tipo: "urgencia",
        contenido: `- REPOSO RELATIVO. 
- USO DE COJIN PICARON
- REPOSO DEPORTIVO POR 3 SEMANAS 
- CELECOXIB  200 MG. 1 COMPRIMIDO CADA 12 HORAS VÍA ORAL POR 5 DÍAS.
- PARACETAMOL 500 MG. 2 COMPRIMIDOS CADA 8 HORAS VÍA ORAL POR 5 DÍAS.
- CONTROL EN APS EN 2 SEMANAS PARA EVALUACIÓN CLÍNICA
- CONSULTAR EN URGENCIAS S.O.S. SE EXPLICAN SIGNOS DE ALERTA.`
    },

    {
        id: 107,
        titulo: "LUXACIÓN DE CODO",
        tipo: "urgencia",
        contenido: `- REPOSO RELATIVO. 
- USO VALVA/YESO BP Y  CABESTRILLO POR 3 SEMANAS
- CELECOXIB 200 MG . 1 COMPRIMIDO CADA 12 HORAS VÍA ORAL POR 5 DÍAS.
- PARACETAMOL 500 MG. 2 COMPRIMIDOS CADA 8 HORAS VÍA ORAL POR 5 DÍAS.
- CONTROL EN POLICLÍNICO DE TRAUMATOLOGÍA HHHA EN 2 SEMANAS (MÓDULO D DEL CDT). EQUIPO DE CODO CON RX.
- CONSULTAR EN URGENCIAS S.O.S. SE EXPLICAN SIGNOS DE ALERTA.`
    },
    
    {
        id: 108,
        titulo: "FRACTURA DE CADERA / ACETABULO HHHA",
        tipo: "urgencia",
        contenido: `- RÉGIMEN HIPOSÓDICO HIPOGLUCÍDICO.
- REPOSO ABSOLUTO.
- CONTROL DE SIGNOS VITALES CADA 8 HORAS.
- PARACETAMOL 500 MG. 2 COMPRIMIDOS CADA 8 HORAS VÍA ORAL.
- DIPIRONA 1 GRAMO CADA 8 HORAS VÍA ENDOVENOSA.
- TRAMADOL 100 MG ½ AMPOLLA CADA 8 HORAS VÍA ENDOVENOSA.
- ONDANSETRON 4 MG S.O.S. VÍA ENDOVENOSA.
- ENOXAPARINA 40 MG AL DÍA POR VÍA SUBCUTÁNEA.
- MEDIAS ANTITROMBÓTICAS.
- MEDIDAS PREVENTIVAS DE ÚLCERAS POR PRESIÓN.
- EXÁMENES PREOPERATORIOS TOMADOS EN S.U.A. 
- CONSENTIMIENTO INFORMADO
- PENDIENTE PROGRAMAR RESOLUCIÓN QUIRÚRGICA.`
    },
    
    {
        id: 109,
        titulo: "FRACTURA DE CADERA NODO",
        tipo: "urgencia",
        contenido: `- HOSPITALIZAR EN NODO
- RÉGIMEN HIPOSÓDICO HIPOGLUCÍDICO.
- REPOSO EN CAMA 
- CONTROL DE SIGNOS VITALES CADA 8 HORAS.
- PARACETAMOL 500 MG. 2 COMPRIMIDOS CADA 8 HORAS VÍA ORAL.
- DIPIRONA 1 GRAMO CADA 8 HORAS VÍA ENDOVENOSA.
- TRAMADOL 100 MG ½ AMPOLLA CADA 8 HORAS VÍA ENDOVENOSA SOS
- ONDANSETRON 4 MG S.O.S. VÍA ENDOVENOSA.
- ENOXAPARINA 40 MG AL DÍA POR VÍA SUBCUTÁNEA.
- OMEPRAZOL 20 MG AL DÍA VÍA ORAL
- MEDIAS ANTITROMBÓTICAS.
- MEDIDAS PREVENTIVAS DE ÚLCERAS POR PRESIÓN.
- EXÁMENES PREOPERATORIOS 
- EVALUACIÓN POR TRAUMATÓLOGO HOSPITAL DE ORIGEN 
- PENDIENTE PROGRAMAR RESOLUCIÓN QUIRÚRGICA DIFERIDA`
    },

    {
        id: 110,
        titulo: "FRACTURA DE PELVIS ESTABLE",
        tipo: "urgencia",
        contenido: `- REPOSO RELATIVO ASISTIDO. MARCHA CON ANDADOR (GESTIONAR EN CONSULTORIO).
- SI ROMMENS I CARGA A TOLERANCIA, SI ROMMENS II 1 SEMANA REPOSO ABSOLUTO, LUEGO CARGA PARCIAL CON AYUDAS TECNICAS. 
- PARACETAMOL 500 MG. 2 COMPRIMIDOS CADA 8 HORAS VÍA ORAL POR 5 DÍAS.
- CELECOXIB 200 MG. 1 COMPRIMIDO CADA 12 HORAS VÍA ORAL POR 3 DÍAS.
- ENOXAPARINA 40 MG AL DÍA POR VÍA SUBCUTÁNEA (MANTENER HASTA CONTROL CON TRAUMATÓLOGO. GESTIONAR RESTO DE RECETA EN CONSULTORIO DE ORIGEN).
- MEDIAS ANTITROMBÓTICAS (GESTIONAR EN CONSULTORIO).
- MEDIDAS PREVENTIVAS DE ÚLCERAS POR PRESIÓN.
- CONTROL EN POLICLÍNICO TRAUMATOLOGÍA POLICHOQUE HOSPITAL DE ORIGEN  EN 2 SEMANAS. SE ENTREGA ORDEN DE RADIOGRAFÍA.
- CONSULTAR EN URGENCIAS S.O.S. SE EXPLICAN SIGNOS DE ALERTA.`
    },

    {
        id: 111,
        titulo: "HIPERKALEMIA",
        tipo: "hospitalizados",
        contenido: `Causas: lisis celular/tumoral, rabdomiolisis, acidosis metabólica, oligoanuria, espironolactona, hipoaldosteronismo

ECG: T picudas, P planas, PR largo, QRS ancho 
    ⁃ Tratar en K > 6 o ECG alterado

Si no es la kalemia esperada, repetir examen (perfil crítico)
    ⁃ Gluconato de calcio 10% 1 amp c/15 min hasta normalizar ECG, luego c/1 h
    ⁃ Solución polarizante 500 ml SG 10% o 250 ml SG 20% + 10 UI insulina cristalina
    ⁃ Salbutamol NBZ (1 ml + 3 ml SF) por 10-20 min por 3 veces
    ⁃ Si acidosis metabólica, bicarbonato de Na 1 ampolla 10 ml
    ⁃ Resinas de intercambio ⁃ Lactulosa (emergencia)`
    },
    
    {
        id: 112,
        titulo: "HIPOKALEMIA",
        tipo: "hospitalizados",
        contenido: `Causas: Síntesis celular (leucemias), insulina, b-agonistas, hipertiroidismo, alcalosis metabólica, diarrea, poliuria, diuréticos de asa o tiazídicos, hipoMg, hiperaldosteronismo

ECG: Descenso ST, T aplanado, aparece U, prolongación QT 
    ⁃ Leve: Slow K 600-1200 mg c/8 hrs 
    ⁃ Moderada: KCl 3 g en 250 ml SF (160 mEq/L) o KCl 4 g en 500 ml SF (107 mEq/L) + añadir MgSO4 o medir Mg 
    ⁃ Severa: KCl carga a 3 g/h (40 mEq/h) por CVC // *1 g = 13.4 mEq

Recomendación: concentración K <60 mEq/L, 2 amp en 500 ml (53.6 mEq/L)`
    },

    {
        id: 113,
        titulo: "HIPERCALCEMIA",
        tipo: "hospitalizados",
        contenido: `Causas: hiperPTH primario (adenoma, hiperplasia, carcinoma), otros hiperPTH, tumoral (PTHrp, osteolisis, producción de calcitriol), fármacos (tiazidas, vitD, VitA, litio), hiperT, ISR, feocromocitoma

ECG: QT corto, bradicardia, BAV 2do grado o completo 
    ⁃ Leve/moderada: Suspender fármacos, hidratación SF (200-500 cc/h), diuréticos de asa, dieta 
    ⁃ Severa: Bifosfonatos (pamidronato 60-90 mg en 50-200 ml SF o SG 5% en 2 h, corticoides (hidrocortisona 200-400 mg/día por 3-5 días, luego prednisona 20-40 mg/día), calcitonina, denosumab, TRR (en Ca>18)`
    },
    
    {
        id: 114,
        titulo: "HIPOCALCEMIA",
        tipo: "hospitalizados",
        contenido: `Causas: HipoPTH (post qx, sd poliglandular ai, iatrogenia, metástasis), déficit vitD (carencial, malabsortción eii, enf celiaca) hipoMg, fármacos (bifosfonatos, diuréticos de asa, corticoides, fenitoína, cisplatino)

ECG: QT largo, T(-), TV, arritmias 
    ⁃ Asintomática: Carbonato de Ca (40% Ca elemental) + calcitriol (metabolito activo) 
    ⁃ Sintomática o Ca <7 o Ca <7.5 + ECG: Bolo 1-2 amp gluconato de Ca en 100 ml SF ev en 20 min, luego BIC 11 amp (990 mg Ca) en 1000 ml SG 5% o 6 amp (540 mg Ca en 500 ml SG 5% a 0.5-1 ml/kg/h. Al mismo tiempo inicial Ca vía oral 
    
1 amp gluconato de Ca (10 ml al 10%): 90 mg de Ca
Control de Ca en 4-5 hrs luego de BIC
Máximo 500 mg de Ca elemental por dosis vía oral`
    },
    
    {
        id: 115,
        titulo: "HEMORRAGIA DIGESTIVA ALTA (HDA)",
        tipo: "hospitalizados",
        contenido: `⁃ Omeprazol bolo 80 mg, luego 40 mg c/6-12 hrs
⁃ Terlipresina bolo 2 mg, luego 1-2 mg c/4-8 hrs (variceal)
⁃ Noradrenalina (no variceal)
⁃ Ceftriaxona 1 g c/24 hrs por 7 días (variceal)`
    },

    {
        id: 116,
        titulo: "INFARTO AGUDO AL MIOCARDIO (IAM)",
        tipo: "hospitalizados",
        contenido: `- ATV vo 80 mg vo
⁃ AAS vo 250-300 mg, 100 mg c/24 hrs
⁃ Clopidogrel vo 300 mg carga, 75 mg c/24 hrs
⁃ Nitroglicerina BIC 50-100 mg en 250 ml SF a 6 ml/h, titular según dolor
⁃ Enoxaparina ev 40 mg bolo, 1 mg/kg sc c/12 hrs hasta revasculatizacion o alta
⁃ HNF bolo 80 UI/kg, luego BIC 18 UI/kg/h
⁃ Tenecteplase 0.5 mg/kg bolo único en 5-10 seg, luego bolo SF 10 ml

Doble antiagregacion por 12 meses, luego AAS
Tenecteplase usar 1/2 dosis en >75 años`
    },
    
    {
        id: 117,
        titulo: "TAQUICARDIA PAROXISTICA SUPRAVENTRICULAR (TPSV)",
        tipo: "hospitalizados",
        contenido: `⁃ Adenosina 6 mg, si no revierte 12 mg (máximo 2 veces)
Verapamilo 5 mg en 5-15 min`
    },

    {
        id: 118,
        titulo: "TAQUICARDIA VENTRICULAR",
        tipo: "hospitalizados",
        contenido: `⁃ Amiodarona 150 mg en 10 min, luego 1 mg/min por 6 hrs, luego 0.5 mg/min por 18 hrs
⁃ Lidocaína 1-1.5 mg/kg a 50 mg/min
⁃ Procainamida 20-50 mg/min (max 15 mg/`
    },
    
    {
        id: 119,
        titulo: "BRADIARRITMIA",
        tipo: "hospitalizados",
        contenido: `⁃ Corregir la causa
⁃ Atropina 0.5 mg cada 3-5 min (actua en el nodo)
⁃ Adrenalina 20-50 ug bolo (actua en todo el miocardio)
⁃ Parche marcapasos / MP transvenoso`
    },
    
    {
        id: 120,
        titulo: "INSUFICIENCIA CARDIACA AGUDA (ICA)",
        tipo: "hospitalizados",
        contenido: `⁃ O2 VMNI
⁃ Furosemida 20-40 mg ev, si no responde, duplicar dosis
⁃ Nitroglicerina (en PAS>110)
⁃ Dobutamina 2-20 ug/kg/min (b1)
⁃ Milrinona 0.375-0.75 ug/kg/min (i PDE-3)

Evaluar natriuresis a las 2 hrs >50-70 mEq/L
Evaluar diuresis a las 6 hrs >100-150 ml/`
    },
    
    {
        id: 121,
        titulo: "CETOACIDOSIS DIABÉTICA (CAD)",
        tipo: "hospitalizados",
        contenido: `⁃ SF 1000 ml en 1 hr, 500 ml en 4 hrs, 250 ml/h hasta corrección acido base
⁃ Insulina cristalina 0.1 UI/kg bolo, luego 0.1 UI/kg/h o 0.14 UI/kg/h
    Control de glicemia c/1 h, buscar descenso 50-70 mg/dL/h
⁃ Si K >5.2, no dar K
⁃ Si K 3.3-5.2, KCl 20-30 mEq/L
⁃ Si K <3.3, KCl 20-30 mEq/h`
    },
    
    {
        id: 122,
        titulo: "CONTENCIÓN",
        tipo: "hospitalizados",
        contenido: `⁃ Lorazepam 4 mg ev/im
⁃ Olanzapina 10 mg vo/im
⁃ Diazepam 10 mg e`
    },

    {
        id: 123,
        titulo: "ESTATUS EPILEPTICO",
        tipo: "hospitalizados",
        contenido: `Manejo de Urgencias:
    - 0-5': ABCDE + HGT + Monitorización (+ECG), O2, laboratorio
    - 6-10': glucosa 50 gr + tiamina 100 mg Ev/ lorazepam 4 mg ev en 2' (repetir a los 5')/ si no hay via: DZP 20 mg rectal o MDZ 10 mg intranasal, bucal o im
    - 10-20': fosfenitoina 20 mg/kg ev a 150 mg/min o fenitoína 20 mg/kg en bolo luego BIC 50 mg/min
    - 10-60': BIC MDZ 0,2 mg/kg carga, bolo c/5' hasta parar dosis o hasta 10 mg/kg; o propofol carga 1-2 mg/kg, repetir bolos 1-2 mg/kg c/ 3-5' max 10mg/kg; o FNB 20 mg/kg ev a 50-100 mg/min; o valproico 30-40 mg/kg en 10'
    - Carga con levetiracetam 2 gr ev y luego según peso, 1 gr c/8 hrs.

Fármacos:
    ⁃ Lorazepam 0.1 mg/kg ev
    ⁃ Midazolam 10 mg im
    ⁃ Levetirazetam 60 mg/kg (max 4500 mg)
    ⁃ Ac Valproico 40

PUNCIÓN LUMBAR (PL): fiebre, cefalea severa, persistencia compromiso de conciencia, inmunosuprimido`
    },
    
    {
        id: 124,
        titulo: "INFECCION URINARIA (ITU)",
        tipo: "hospitalizados",
        contenido: `Baja 
    ⁃ Ciprofloxacino 500 mg c/12 hrs por 3 días
    ⁃ Nitrofurantoína 100 mg c/8 hrs por 5 días
    ⁃ Cefadroxilo 1 g c/12 hrs por 5 días
    
Alta
    ⁃ Ceftriaxona 2 g c/24 hrs ev
    ⁃ Ciprofloxacino 500 mg c/12 hrs
    
Profilaxis
    ⁃ Postcoital: ciprofloxacino/nitrofurantoína/cotrimoxazol
    ⁃ Continua: nitrofurantoína/cotrimoxazol 1 comp 3 veces/semana por 6 meses`
    },
    
    {
        id: 125,
        titulo: "ERRADICACION HELICOBACTER PYLORI",
        tipo: "hospitalizados",
        contenido: `Cuadriterapia c/bismuto (14 días)
    ⁃ Omeprazom 40 mg c/8 hrs
    ⁃ Amoxicilina 1 g c/8 hrs
    ⁃ Metronidazol 500 mg c/8 hrs
    ⁃ Subsalicilato de Bismuto 20 ml c/8 hrs

Terapia Dual (14 días)
    ⁃ Omeprazol 40 mg c/8 hrs
    ⁃ Amoxicilina 1 g c/8 hrs

Cuadriterapia concomitante (14 días)
    ⁃ Omeprazol 40 mg c/12 hrs
    ⁃ Amoxicilina 1 g c/12 hrs
    ⁃ Metronidazol 500 mg c/8 hrs
    ⁃ Claritromicina 500 mg c/12 hrs

*Ag en deposiciones en 6-8 semanas`
    },
    
    
    {
        id: 126,
        titulo: "DISPEPSIA",
        tipo: "hospitalizados",
        contenido: `<40 años sin signos de alarma
    ⁃ Erradicación H. pylori 
    ⁃ Prueba terapéutica IBP: Omeprazol 40 mg c/24 hrs por 8 sem
    ⁃ Si no hay respuesta, endoscopía + ecografía abdominal

DISPEPSIA FUNCIONAL
    ⁃ Distres postprandial:
    ⁃ Dolor epigastrico: Omeprazol`
    },
    
    {
        id: 127,
        titulo: "MENINGITIS",
        tipo: "hospitalizados",
        contenido: `⁃ Ceftriaxona 2 g c/12 hrs
⁃ En inmunocompronetido o embarazada agregar ampicilina 2 g c/4 hrs
⁃ Dexametasona 10 mg c/6 hrs por 4 dias
⁃ Aciclovir 10 mg/kg c/8 hrs`
    },

    {
        id: 128,
        titulo: "CELULITIS/ERISIPELA/FASCEITIS",
        tipo: "hospitalizados",
        contenido: `Ambulatorio (5-7 días)
    ⁃ Cefadroxilo 1 g c/12 hrs
    ⁃ Amoxicilina/Ac Clavulánico 875/125 mg c/12 hrs
    ⁃ Flucloxacilina 500 mg c/8 hrs
    ⁃ Alergia: Clindamicina 600 mg c/8 hrs

Hospitalizado
    ⁃ Penicilina 2-4 mill + cloxacilina 2 g c/6 hrs
    ⁃ Cefazolina 2 g c/8 hrs
    ⁃ + Clindamicina 600 mg c/8 hrs en caso grave
    ⁃ Ampicilina/Sulbactam 2 frascos c/8 hrs

Fasceitis Necrotizante
    ⁃ Ceftriaxona + metronidazol (tipo I polimicrobiana)
    ⁃ Ceftriaxona + clindamicina (tipo II monomicrobiana)`
    },
    
    {
        id: 129,
        titulo: "ENDOCARDITIS INFECCIOSA",
        tipo: "hospitalizados",
        contenido: `Empírico
    ⁃ Ampicilina 12 g/día en 4 dosis + cloxacilina 12 g/ día en 4-6 dosis + gentamicina 1 mg/kg c/8 hrs

SAMS VN (4-6 semanas)
    ⁃ Cloxacilina 12 g/día en 4-6 dosis o cefazolina 6 g/día en 3 dosis

SAMR VN (4-6 semanas)
    ⁃ Vancomicina 30-60 mg/kg/día en 2-3 dosis

S. viridans/gallolyticus VN (4 semanas)
    ⁃ Penicilina G 24 mill/día en 4-6 dosis o amoxicilina 12 g/día en 6 dosis o ceftriaxona 2 g/día
    ⁃ Asociado a gentamicina 3 mg/kg/día en 1 dosis por 2 semanas

Enterococcus VN (4-6 semanas)
    ⁃ Ceftriaxona 2g c/12 hrs + ampicilina 3 g c/6 hrs
    
En válvula protesica se trata por 6 semanas + rifampicina y gentamicina 2 sem en S. aureus o solo gentamicina 2 semanas enterococcus
`
    },
    
    {
        id: 130,
        titulo: "ANALGESIA/FÁRMACOS",
        tipo: "hospitalizados",
        contenido: `Oral
    ⁃ Paracetamol 1 g c/8 hrs
    ⁃ Diclofenaco 50 mg c/8 hrs
    ⁃ Ibuprofeno 400 mg c/8 hrs
    ⁃ Meloxicam 7.5 mg c/12 hrs
    ⁃ Naproxeno 550 mg c/12 hrs
    ⁃ Loratadina 10 mg c/24 hrs noche
    ⁃ Clorfenamina 4 mg c/24 hrs noche
    ⁃ Metoclopramida 10 mg c/8 hrs

Endovenosa
    ⁃ Ketorolaco 30 mg
    ⁃ Metoclopramida 10 mg
    ⁃ Dipirona / metamizol 1 g
    ⁃ Viadil (pargeverina 5 mg +/- metamizol 1 g)
    
Laxantes
    ⁃ Lactulosa 20 ml c/8 hrs (en EH 30-45 ml c/6-12 hrs para 2-3 dep blandas/día) 
    ⁃ PEG 17 g c/24 hrs`
    },
    
    {
        id: 131,
        titulo: "PROBLEMAS DE COAGULACIÓN/PREPARACIÓN PABELLÓN",
        tipo: "hospitalizados",
        contenido: `Fitomenadiona (VitK)
    - 2 amp EV, dsp 1 amp c/8hrs x 3 días (tomar hemograma de control)
    - Si no existe respuesta favorable, usar plasma fresco congelado`
    },
    
    {
        id: 132,
        titulo: "TVP",
        tipo: "hospitalizados",
        contenido: `ARMAR BOMBA DE HEPARINA
    - bolo 80 mg/kg max 5000 UI de heparina NF, luego 25.000 UI HNF en 250 cc a 8 ml/ hr.
        - Ajustar según TTPK cada 6 hrs inicialmente
    - clexane 1 mg/kg c/12 hrs (enoxaparina; usar dalteparina ante crea >1.2)`
    },

    {
        id: 133,
        titulo: "BOMBA DE INSULINA",
        tipo: "hospitalizados",
        contenido: `100 UI ins. Cristalina en 100cx SF a 70 ml /ml
0,1 x kg ( para calcular)`
    },
    
    {
        id: 134,
        titulo: "ANTICOAGULACIÓN POR FIBRILACIÓN AURICULAR (AC X FA)",
        tipo: "hospitalizados",
        contenido: `- Carga -> de 300 mg de amiodarona en 100 SF pasar en 20 min
- Bomba -> 900 amiodarona 500 SG 5% en 20 ml/ hr. ( 24 hrs)`
    },
    
    {
        id: 135,
        titulo: "HIPOGLICEMIA",
        tipo: "hospitalizados",
        contenido: `- 20-40 mg/dl -> 3 ampollas SG 30%
- 40-60 mg/dl -> 2 ampolla SG 30%`
    },
    
    {
        id: 136,
        titulo: "SECUENCIA DE INTUBACIÓN RÁPIDA",
        tipo: "hospitalizados",
        contenido: `"SOFAME" -> éxito (succión, oxigeno, fcos, vía aérea, medicamentos, equipo)
    - Preoxigenación: 5', permite 3-5' de apnea
    - Pretratamiento: lidocaína 1,5mg/kg; fentanilo 2-3 ug/kg (ambos 3' antes intubación)
    - Inducción y parálisis: ketamina 1,5mg/kg (ideal en hipotensión, efecto analgésico); propofol 1,5mg/kg (rápido inicio acción y corta duración; produce hipotensión, bradicardia, hipoxemia y apnea); midazolam 0.3mg/kg (inicio acción lento, depresión respiratoria y apnea)
    - Relajante muscular: succinilcolina 1 - 1,5 mg/kg (evitar en hiperkalemia); rocuronio 1 - 1,2 mg/kg (inicio accion rápido 45-60 seg, sin contraindicaciones)
    - Fijación tubo`
    },
    
    {
        id: 137,
        titulo: "BIC DE MORFINA/ANALGESIA",
        tipo: "hospitalizados",
        contenido: `- 25 mg de morfina (2 ampollas y media) en 250 cc de SF a pasar a 10 cc/hr(se pasa continuamente 1 mg por hora)
- Dilución: 1 ampolla de morfina (10mg/cc) se  lleva a 10 cc con SF en una jeringa de 10 (es decir el cc de la ampolla mas 9 cc de SF) (así te queda 1mg por cc)`
    },

    {
        id: 138,
        titulo: "CONSTIPACIÓN",
        tipo: "hospitalizados",
        contenido: `Gastroenterologia:
    - existen dificultad en el manejo de la deposiciones en los pacientes con sedación y BNM prolongada
    - hay reportes inclusive de perforaciones colonicas en algunas UPC de la RM
    - no tenemos muchas opciones en el arsenal farmacológico del HHHA
    - siempre corregir las alteraciones hidroelectroliticas

Recomendación:
    - En todo paciente que se inicie opioides altas dosis y/o bloqueo neuro muscular debería paralelamente iniciarse domperidona 10 mg cada 8 horas ev. + lactulosa 20-40 cc cada 8 horas
    - Meta: 1-2 deposiciones día
    - la asociación domperidona más metoclopramida no ha demostrado ser más efectiva. Inclusive aumenta los eventos cardiovasculares (prolongación qT) por lo que se desaconseja.
    - Si a las 48 horas no hay deposiciones HAY QUE HACER TACTO RECTAL y:
        - Solución PEG 1-2 sobres al dia. (No siempre hay stock disponible)
        - Enema lactulosa (200/300 cc lactulosa en 500 cc SF.
        - si no funciona, repetir enema lactulosa con mayor volumen ( hasta 1000 cc SF)
        - Si a pesar de estar medidas hay ausencia de deposiciones a las 72- 96h: evaluar por Gastroenterologia
        - Con estas medidas podríamos resolver casi la gran mayoría  del manejo de de deposiciones`
    },
    
    {
        id: 139,
        titulo: "MANEJO POST ACV AHA 2021",
        tipo: "hospitalizados",
        contenido: `- P/A: Inicio de AntiHTA para metas de PA: <130/80
- Inicio precoz en condiciones comórbidas: IAM, Disección AO, Preclampsia, etc.
- Sin terapia reperfusión P/A > 220/120 sin comorbilidades = razonable disminuir PA 15% primeras 24 hrs.
- P/A < 220/120 e inicio de antiHTA en primeras 72 hrs. no ha sido eficaz para reducir muerte o discapac. (SCATS 2011, COSSACS 2012)

Antiplaquetarios:
- AAS: (IST – CAST) reducción stroke/muertes con AAS en las primeras semanas (dosis > 160 mg/día)
- NNT 79-80 para stroke/muerte en 2ª-4ª semana
- Atorvastatina 80 mg/día para meta de LDL <100 o <70 si RCA alto y control de perfil lipídico cada 3 meses. (SPARCL 2006 – disminuye el riesgo de ACV, NNT: 46 en 5 años para prevenir ACV)
- Temperatura: dar antipiréticos si > 37,5º (Fiebre= aumento mortalidad intrahospitalaria)
- Glicemia: meta 140-180 mg/dL; tratar > 60 mg/dL; Hiperglicemia 24 hrs inciales à peor resultado`
    },
    
    {
        id: 140,
        titulo: "HIPOFOSFEMIA",
        tipo: "hospitalizados",
        contenido: `0.5meq/lit
- 2 ampollas en 6 hrs
- Fósforo bajo 1`
    },
    

    {
        id: 141,
        titulo: "URGENCIA DIALÍTICA (CRITERIOS)",
        tipo: "hospitalizados",
        contenido: `- A: Acidosis pH<7,2
- E: ELP K >6,5 /ECG
- I: Intoxicaciones
- O: Overload: EPA
- U: Uremia :encefalopatia uremica / pericarditis / derrame pleural`
    }
];
